---
title: risk appitite
author: ''
date: '2018-06-21'
slug: risk-appitite
categories: []
tags: []
---



The regulatory landscape for banking and insurance
firms – be it speeches, working papers and draft or
final regulation – is full of references to risk appetite,
its benefits, uses, applications and case studies of
failed firms whose weak risk appetite frameworks
played a part in their downfall.
When firms are criticised for shortcomings in their risk
governance and management, an appetite framework
is commonly prescribed as a cure by regulators. And
yet, there remains a surprising variety of opinion
about what it actually means to establish and embed
a proper risk appetite framework.
While the concepts and themes discussed in this paper
will be of interest to all financial institutions, this paper
is particularly focused on the banking sector. Our goals
in this paper are five-fold:
(1) To summarise the arguments in favour of risk
appetite frameworks.
We see tremendous practical benefit in adopting and
embedding risk appetite within financial institutions
(and indeed more widely across corporates and
governments, but that is for another time). We believe
that, on this occasion, received wisdom has it right: risk
appetite frameworks support conscious and profitable
risk-taking and help avoid catastrophic failures.
(2) To highlight the emerging consensus on the core
concepts of risk appetite between regulators and
firms within the financial services industry.
After a period of some uncertainty, a consensus is now
emerging around the definition of key terms in the
risk appetite approach. Although specific risk appetite
language will need to vary from firm to firm (reflecting
internal communication needs), the building blocks
are taking shape for a common set of notions that
will allow a meaningful dialogue between financial
institutions and regulators.
(3) To illustrate what we think ‘good’ looks like for a
risk appetite framework.
A risk appetite framework is good to the extent that it
allows the people who set a firm’s strategy to accept
in a conscious way the risks that correspond with that
strategy.
It’s good to the extent that people within a firm who take
risks on its behalf know what strategic objective they are
supporting in their risk-taking; and keep within agreed
limits. It’s good to the extent that all of a firm’s material
risks are understood, along with the drivers of those risks.
And it’s good to the extent that risk appetite language
and culture permeate the firm, its decision-making
processes and the understanding of its own performance.
(4) To suggest ways to spot a ‘genuine’ risk appetite
framework, by giving examples of the sorts of hardheaded
questions we would expect regulators and
Non-Executive Directors to be asking firms about
their risk appetite frameworks.
It is relatively easy for a firm to relabel or rebadge
existing risk management limits and presents them
for approval to its Board and regulators as a ‘risk
appetite framework’. Given the large array of
competing demands on management attention, this
may seem to be enough. And it may also buy time
with the regulator. But such an approach is a long
way from our understanding of a genuine risk appetite
framework. Because it is a pale imitation of the real
thing, it will naturally deliver only a fraction of the
benefits. To test if a particular risk appetite framework
is genuine, executives or regulators should probe how
deeply the concepts and language of risk appetite
have taken root up and down the firm.
(5) To suggest what risk appetite might look like in
three to five years’ time, based on the trajectory of
regulation and trends in the banking and insurance
industries.
Following our review of regulatory pronouncements,
policy papers, speeches and both draft and final
regulation, we suggest that risk appetite may well
become the primary lens through which the quality of
a firm’s risk management framework, governance and
culture is assessed. From capital planning to data quality,
from governance to strategy, sustainability, remuneration
and public disclosure, the applications for risk appetite
are far and wide. Firms should expect to be judged on
the strength of their risk appetite framework. Executive
and Non-Executive Directors should be preparing for the
heightened prominence of risk appetite. This is becoming
a ‘must-have’ not a ‘nice-to-do’.
Introduction
Everyone these days seems to agree that risk appetite frameworks are
good things – even if no-one can quite agree what a good one looks like.
Risk appetite frameworks How to spot the genuine article 1
To start a new section, hold down the apple+shift keys and click
to release this object and type the section title in the box below.
1. The arguments in favour of
risk appetite frameworks
There are both ‘push’ and ‘pull’ arguments for firms to
improve their risk appetite frameworks.
The ‘push’ arguments come from the slew of recent
or forthcoming regulation and supervisory guidance
that will compel firms to improve the way that their risk
appetite frameworks operate – or in some cases build
this capability from scratch. We summarise these in
section 5 of this paper. Credit rating agencies also keep
a watchful eye on firms’ risk appetite capability as part
of the credit rating process.
Just as importantly, however, the ‘pull’ arguments
come from the firm-wide benefits that accrue once risk
appetite is properly embedded within an organisation.
Evidence from the credit crisis
As the Financial Stability Board (FSB) has noted of some
firms during the financial crisis, “without the appropriate
checks and balances provided by the Board, the risk
management function, and independent assessment
functions, a culture of excessive risk-taking and leverage
was allowed to permeate in these weakly governed
firms”1
 .At the highest level, the people in charge of
running banks need to have a solid understanding of
the risks their firms as a whole are taking.
“A key weakness,” according to the Senior Supervisors
Group (SSG), “was a disparity between the risks that
their firms took and those that their Board of Directors
perceived the firms to be taking… Supervisors saw
insufficient evidence of active Board involvement
in setting the risk appetite for firms in a way that
recognises the implications of that risk-taking.”2
 It is
critical that the Chief Executive and Board members
understand and consider the risk appetite and the
risks being taken for the potential returns in evaluating
major business decisions.
In other words, management and the Board must
know beforehand the firm’s capacity for risk-taking,
the previously specified amount of different risks they
want the firm to take and the current and targeted risk
profile relative to the desired level and capacity – to be
able to evaluate and take action.
This is – in essence – what a risk appetite framework
does for an organisation. Information needs to flow
up to the Board and be presented in a timely way that
drives decision making.
In the words of the FSB, “many Boards did not
pay sufficient attention to risk management or set
up effective structures, such as a dedicated risk
committee, to facilitate meaningful analysis of the
firm’s risk exposures and to constructively challenge
management’s proposals and decisions... The
information provided to the Board was voluminous and
not easily understood which hampered the ability of
Directors to fulfil their responsibilities.”3
 Here, too, is
where a risk appetite framework earns its keep. It puts
the Board in the driving seat, giving it the responsibility
and the tools for setting, communicating and cascading
down the firm its stated strategic plan and business
objectives and appetite for specific risks.
At the same time, a fully-functioning risk appetite
framework establishes a firm-specific quality and style
of internal communication that enables risk messages
to feed up the organisation from the people who take
or manage risk.
As the SSG found, “in some of the firms that felt most
confident in their risk identification practices during the
market turmoil and that avoided material unexpected
losses through year-end 2007, senior managers
promoted a continuous dialogue between business
areas and risk management functions at the top of the
firm on whether the firm was achieving an appropriate
balance between its risk appetite and risk controls.”4

Firms with effective risk appetite frameworks were
protected from the worst of the credit crisis because
they avoided excessive concentrations and were able
to react quickly to deteriorating conditions, whether by
hedging their positions or taking out their pipelines.
The business strategy was clear, the risk implications
were understood and a common risk culture kept firms’
diverse and numerous employees working towards
shared goals.
Conscious risk-taking
No business can thrive without taking on risks. A key
benefit of deploying a risk appetite framework is that
these risks are identified and quantified in a structured
way that relates them to the firm’s business objectives
and strategy.
By deploying a properly embedded risk appetite
framework, a firm can choose to take on particular
amounts of particular risks, in line with its overall
business strategy and in contrast to passive risk-taking.
1 Thematic review on risk
governance, Peer review
report, FSB, February 2013
2 Risk Management Lessons
from the Global Banking
Crisis of 2008, SSG,
October 2009
3 Thematic review on risk
governance, Peer review
report, FSB, February 2013
4 Observations on risk
management practices
during the recent market
turbulence, SSG, March
2008
2
To start a new section, hold down the apple+shift keys and click
to release this object and type the section title in the box below.
The trade-offs between risk and reward in a risk
appetite framework are made up front, in a conscious
attempt to decide the right calibration, and at a firmwide
level.
For some kinds of risk, this is largely routine. Take credit
risk. Every bank knows that not all of its customers will
repay their debts. While it might not be good business
practice to shout about it, the bank can accept the
likelihood of some customers defaulting on their loans
so long as enough of the others repay on schedule,
and so long as the price of offering credit – adjusted
for the risk – covers the cases where customers default.
Defaults are not welcomed, but the possibility of credit
losses is consciously accepted – and can therefore be
quantified and tracked. An appetite for credit losses
can be formulated and limits and triggers can be set to
warn the organisation if actual exposure is moving too
far above or below the desired level (see ‘Risk appetite
in action #1’ below).
What a risk appetite framework does is to extend
this approach to all of a firm’s risks – and work out
the linkages between those risks, its overall strategy
and the lower-level risk drivers of its risk profile.
Capturing the breadth of risk-taking is central to a good
framework (see ‘Risk appetite in action #2’ below).
Risk appetite in action #1
An experienced credit sanctioner within a
large wholesale bank takes a loan application
to the Credit Committee. He recognises that
it’s a significant deal, given the size,
maturity and sector of the obligor.
As he presents the paper, he makes explicit
reference to the risk appetite of the
division, knowing how this supports the risk
objectives of the firm. While the proposed
deal is in some ways outside of current
appetite, the return on capital is higher
than usual for this sort of deal because
competitor banks have reined back lending
in this area. The Committee debates the
proposal using the language of risk appetite
and agrees to the deal on the proviso that
unutilised limits to customers elsewhere in
the same sector are scaled back. As a result,
sector concentration risk appetite limits
remain unchanged, the division maintains
its adherence to the Group’s risk strategy
and the bank has made better use of its risk
taking capacity.
Risk appetite in action #2
The Chief Risk Officer (CRO) of a brokerage
has used the risk identification round of
annual appetite setting to take a fresh look
at the risk profile of her firm – in its fullest
sense. What’s emerged is that one of the
key risk drivers is ‘key person risk’ since the
business is heavily dependent on revenues
generated by a small group of highly
experienced traders.
She knows that the Board has never asked for
information on this risk. Presenting it to them
for the first time will be a challenge. They will
ask hard questions about ‘why now?’ and
‘how do you manage this?’ She also knows
that there are no current ways to measure
or report ‘key person risk’ and that the HR
department has historically backed away from
supplyi
To start a new section, hold down the apple+shift keys and click
to release this object and type the section title in the box below.
‘Have we properly understood how to map our business
objectives to our risk objectives?’
‘If there were to be a breach of our risk appetite limits,
what would be the management actions that could
bring the measure back within appetite?’ and
‘Have the limits and triggers been calibrated well enough
so that those actions would have enough time to take
effect?’
A focus on the drivers of quality risk management
Beyond the benefits to the business in question, it is
easy to see why risk appetite frameworks have been
championed by so many people within the regulatory
community. If you want to diagnose the quality of risk
management, governance and culture at a firm, there is
no better place to start than its risk appetite framework.
To understand why, consider how many things a firm
needs to have, to be good at risk appetite:
• A strong, independent risk function that has the
confidence of its convictions and the internal clout to
design, build, launch and embed risk language and
concepts across the firm; the risk personnel need to be
good at reaching out to their colleagues in the business
lines and advocating the risk appetite perspective;
• A sponsor at the executive level who is powerful
enough to make risk appetite the way the firm approaches
risk. Without senior buy-in from a Chief Executive Officer
(CEO), Chief Finance Officer (CFO) or CRO, risk appetite will
wither on the vine;
• A Board that is prepared to lead, rather than be led or
pacified by the occasional report or sporadic deep dive;
• A Board and executive who can articulate and recognise
financial and non-financial risks in their business model
and strategy;
• A robust process to aggregate risk – both
numerically and conceptually. Risk appetite metrics
rarely need to be correct to the second decimal
place, but risk definitions need to be correct and
uniformly understood across the firm. The people and
processes that identify and aggregate risk need to be
of high calibre to support completeness of coverage –
this should cover financial and non-financial risks;
For example, a financial institution will take on data
quality risk whether it likes it or not. A standard (and
self-defeating) approach to this risk is to exclude it
from the appetite framework and to focus instead on
financial risks, which are more readily measurable. But
a risk appetite framework will encourage the business,
the Board and risk managers to ask difficult questions
and find ways to assess the expected and the stressed
risk position. It is better to have an approximate
measure of data quality risk and an awareness of where
it is most likely to hurt you, than no idea at all.
Furthermore, any redesign of the business model may
raise or reduce data quality risks and these changes
in the risk profile should be made in a conscious, well
informed fashion. Once data quality becomes part of
the landscape of risk appetite and risk measurement,
top-down direction can be given by the Board, and
bottom-up assessments of the business or control
environments can be developed.
Joined-up risk management
Beyond the benefits of breadth, risk appetite
frameworks also provide depth to risk management
activities. It is the collective impact of risk-taking across
a firm that needs to be managed. This will always
require co-ordination between different parts of a firm,
alignment between broader objectives and the more
specific objectives of business units or individuals, and
a translation between the technical language of the risk
or product specialist and the more general firm-specific
risk appetite language.
This is where risk appetite frameworks come to the
fore. Firstly, they facilitate top-down direction from
the Board via the cascading of risk appetite statements
and their ongoing monitoring and control – in a risk
appetite language that is meaningful to everyone.
Secondly, they rely on bottom-up information and
insight from the businesses and control functions
through the calibration of risk appetite limits and
triggers, as well as the reporting of risks and the risk
profile versus risk appetite.
A properly embedded risk appetite framework is also a
‘way’ of doing risk within a firm that keeps it on the front
foot by prompting the right sort of questions:
‘Where is our risk profile changing most quickly?’
‘What are the significant changes to the business,
competitive or control environments?’
4
To start a new section, hold down the apple+shift keys and click
to release this object and type the section title in the box below.
• A well-established methodology to produce risk
adjusted metrics (with the active buy-in of both the
finance and risk departments) so that the risk appetite
perspective takes root outside of the risk department;
• A good capacity for change management, since
embedding risk appetite requires some deep-seated
changes to be made to the way a lot of people go
about their jobs;
• A culture within a firm that enables the free
flow of information up and down the hierarchy.
The bosses are not afraid to hear bad news, nor do
the business units water down messages for fear of
giving offence; and
• A culture that weaves risk considerations into the
rest of the firm in such things as business strategy,
capital planning, day-to-day risk-taking by the business,
governance and the design of remuneration plans.
By making risk appetite the way your firm does risk, you
are naturally drawn to focus on these drivers of success.
Risk appetite frameworks How to spot the genuine article 5
2. The emerging consensus on
risk appetite
After a period of some uncertainty, we see a consensus
emerging around the definition of key terms in the
risk appetite approach. Although specific risk appetite
language may continue to vary from firm to firm,
the building blocks are taking shape for a common
set of notions that will allow financial institutions and
regulators to conduct a meaningful dialogue.
Disagreement about the definition of risk appetite has
certainly hindered its take-up across the industry, but
so have two related factors. There have been few,
if any, unambiguously good examples of risk appetite
frameworks for firms to copy.
Moreover, regulators have been reluctant to spell out
in detail what they expect to see in a risk appetite
framework. This may well be because they have yet
to see a model example to recommend, but just as
importantly, they generally prefer to see how firms are
choosing to think about and apply the concept, rather
than gifting them a ‘tick-box’ approach to compliance.
But the regulators have worked to bring greater clarity
to the terms and discipline to the definitions, as seen in
the February 2013 paper by the FSB: “Thematic Review
on Risk Governance – Peer Review Report”. What is
especially significant about the FSB paper, from a risk
appetite perspective, is that it represents a concerted
effort to establish a common terminology for financial
regulators across the globe. This truly is the future of
risk appetite, as far as supervisors are concerned.
However, even once harmonisation of terms has been
achieved between the regulators and the regulated,
what’s crucial from a firm’s perspective is that it is able
to develop its own ‘dialect’ of risk appetite language.
This clear and unambiguous firm-specific language
is what will foster a common risk culture, based on a
shared understanding of coherent terms –
and reflecting the particular history, structure and
activities of that firm.
The following definitions reflect our understanding of
this emerging consensus.
Risk capacity
The maximum level of risk at which a firm can
operate, while remaining within constraints implied
by capital and funding needs and its obligations to
stakeholders.
No firm should want to operate at its capacity,
since there would be a very real risk of a breach.
Once the capacity has been understood, a crucial task
of risk management is to understand how a firm’s
activities expose it to risks that use up that capacity.
While capacity can be expressed in terms of capital or
liquidity, the obligations the firm has to its stakeholders
– be they the ultimate owners of the firm, its customers
or regulators – are the constraints that can be used to
define capacity.
Risk profile
The firm’s entire risk landscape reflecting the nature
and scale of its risk exposures aggregated within and
across each relevant risk category.
We think it’s important to emphasise that the true
risk profile of a firm can never be known in full. It’s a
multidimensional set of sensitivities to a wide range of
potential risk drivers. But the profile can be estimated by
pertinent, timely and accurate assessments of a firm’s
exposure to risks, taken from many complementary
perspectives – including concentration risk, wrong
way risk and correlations across risk types or scenarios.
Furthermore, knowing the likely shape of your risk
exposures through the cycle can be equally or even more
important than knowing it for a particular point in time.
Risk appetite
The risk a firm is willing to take in the pursuit of
its strategy.
The crucial features of this definition are: ‘willing’,
which denotes a conscious recognition and
acceptance of the risk/return trade-off; ‘pursuit’,
which acknowledges that firms may fail to achieve their
goals, while still bearing the risk; and ‘strategy’ which
highlights how appetite should always be considered in
light of the firm’s overall business model.
6
Risk appetite statement
The articulation of risk appetite in written form.
The crucial word here, in our opinion, is ‘articulation’
because risk appetite statements need careful
wording to achieve an effective cascade down the
firm of Board-level guidance and up the firm of
specific risk information. The goal is to communicate
to staff in firm-specific risk appetite language they
can understand and apply in their daily roles. There
is typically a hierarchy of risk appetite statements,
measures and limits, starting with a high-level
enterprise-wide risk appetite statement which then
cascades down to directional, specific and finally
detailed risk appetite statements, measures and limits.
(See ‘Risk appetite in action #3’).
Risk appetite limit
The level of risk which, if breached by the firm’s
risk profile, would necessitate immediate escalation
and corrective action.
Risk appetite limits are about putting individual
risk-taking in a strategic and firm-wide context and
perspective. They translate strategic objectives into
specific steer and control of risk-taking across and
within the firm’s businesses.
As the notion itself suggests, defining a firm’s risk
appetite is more than just setting an upper risk appetite
limit. A ‘healthy’ risk appetite is not just about helping
the firm to avoid eating more than its capacity to
digest, it’s also about eating enough for the firm to live
and thrive.
Accordingly, risk appetite is best understood as a
range of strategically desired outcomes between the
‘too much’ and the ‘not enough’. This approach
elevates risk appetite from a risk control mechanism
to one which also incorporates strategic risk-taking.
In practice there are different ways of translating a
firm’s high-level risk appetite into a limit and reporting
system cascaded down to the firm’s shop floor.
Proper management attention is obviously needed at
both ends of the range for potential overshooting or
undershooting of the objectives.
Some firms operate a three-leg limit system with a
hard-coded upper limit, a trigger, which if reached
gives rise to escalation and as appropriate corrective
action, and a lower limit also referred to as a target,
defining the minimum risk that should be taken not
least in order to generate sufficient revenues.
An emerging and we believe leading market practice
seems to evolve towards a four-leg system with an
upper and a lower risk appetite limit combined with
related triggers (see overleaf for a more in-depth
discussion of triggers).
Risk appetite in action #3
The CFO of a medium sized bank is drafting
the risk appetite statement that he wants
to present to the Board. The numbers have
been agreed for a while, but it’s the written
description that is causing him to think hard.
What adjective should he use to convey the
firm’s appetite for risk given the growth
plans set out in the business plan? Is the
firm targeting ‘aggressive’ growth? That
might suggest to staff that sales should drive
behaviour at the expensive of risk control.
How about ‘controlled expansion in fastgrowing
markets’? He talks it over with the
CEO and CRO, who jointly agree this term
from a spectrum of plausible terms.
Together, they hone and refine the wording,
conscious of the consequences of alternative
wordings, and what sort of risk behaviours
they might encourage or be seen to sanction.
All of them understand that the language
they use will be cascaded down the firm with
the explicit goal of guiding staff behaviour
and shaping the ethos of the firm.
Risk appetite frameworks How to spot the genuine article 7
To start a new section, hold down the apple+shift keys and click
to release this object and type the section title in the box below.
Obviously, breaching any of these thresholds may
require a strategic reassessment of the business,
its potential and the level of allocated capital and
other resources rather than a simple heuristic
response. Depending upon the market environment,
overshooting but also undershooting the strategic
objective may be just the right thing to do. In such
cases, the necessary corrective action is reformulating
the strategy and the limits, not reducing or increasing
the risk-taking. Whatever the firm-specific solution to
setting risk appetite limits may look like, it is crucial
for an efficient and effective risk appetite framework
that any deviations from the strategic business and risk
objectives are picked up and acted upon.
It should be noted that a number of regulatory papers
use the terms ‘risk appetite’ and ‘risk tolerance’
synonymously, while others make a distinction between
the two. The papers that make a distinction suggest
that ‘risk tolerance’ refers to a firm’s attitude towards
certain types of non-financial risks (e.g. operational or
reputational) which are not actively taken but are only
tolerated. We suggest that ‘non-financial risks’, as well
as ‘financial risks’, should be taken consciously and that
risk appetite statements, and (where possible) measures
and limits, should be assigned to them. As a result,
we do not use the term ‘risk tolerance’.
Profile
Upper limit
Upper trigger
Capacity
Appetite
Profile
Objective
under threat
Capacity
Appetite
Profile
Escalation
Appetite
Capacity
Appetite
Profile
Desired range
Capacity
Profile
Objective
under threat
Appetite
Lower trigger
Lower limit
Risk profile is less than
the lower limit.
Corrective action
must be taken
Risk profile is between
the upper and lower
triggers
Risk profile is between
the upper trigger and
limit. Escalation to
consider corrective
action
Risk profile exceeds
the upper limit.
Corrective action must
be taken
Risk profile exceeds
risk capacity. The firm
must enact its
Recovery and
Resolution Plan
Acceptable
range for
risk profile
Capacity
Figure 1. Risk appetite concepts at a glance
Firm is unviable
Risk appetite trigger
The level at which escalation occurs to a higher
forum, committee or level of authority because the
risk profile is sufficiently close to the risk appetite
limit that corrective action should be considered.
A successful risk appetite framework will encourage
firms to have the courage of their risk convictions.
Once a risk appetite limit is in breach of its trigger,
it should prompt meaningful debate at the next
escalation level. For example, the Board-level triggers
should be discussed by the Board. Lower down
the organisation, there may be a Retail Credit Risk
Committee (RCRC), with its own suite of risk appetite
triggers – only some of which would be escalated to
the Board. The RCRC would debate the reasons and
recommended responses to risk appetite triggers for
those limits that have been predefined as requiring
discussion by the Committee if they are breached.
These concepts of risk appetite, capacity, statement,
limit and trigger combine to form a coherent way of
understanding and communicating risk-taking within
firms, as shown in figure 1.
8
Communicate
Figure 2. Implementing and running a risk 
To start a new section, hold down the apple+shift keys and click
to release this object and type the section title in the box below.
3. What ‘good’ looks like
When push comes to shove, an isolated limit set
outside of a firm-wide strategy may fail to protect it
because there is no overall logic to its calibration.
Once again, it is the aggregated impact of risktaking
across a firm that needs to be managed. Limit
calibration needs to be performed by people who
understand how and why their decisions affect the
firm’s overall risk profile.
Isolated limit setting is a long way from our
understanding of a true risk appetite framework.
The wide-reaching benefits of a risk appetite
framework can only be realised if all of the elements
are in place and if risk appetite has become the way the
firm ‘talks’ and ‘does’ risk.
There are many ways to begin to describe how this
would look and how it would work. You can describe
what needs to be done to implement it from scratch,
or how it would work once up and running. However,
one of the subtleties of risk appetite is the way in which
it encourages firms to reappraise and adjust their risk
positions. What we describe below is not a one-off
process, even if the subsequent iterations may not be
as complex or time-consuming as the first.
At a high level, we begin with the firm’s strategic plan
and objectives (see figure 3 below). Risk management
is at the service of the firm. The risk objectives reflect
what the firm wants to achieve and how it intends
to achieve those aims. Over time, as firms embed risk
appetite, risk considerations become a factor in setting
the firm’s strategic plan, but conceptually, the point
to make is that the risk strategy is set once the firm’s
strategic plan and objectives are set.
Business dimensions
Risk appetite
High-level risk capacity,
risk appetite statements,
measures and limits
Strategic plan & objectives
Risk strategy
Key risk drivers and related
risk appetite statements,
measures and limits
 Principles and policies
to operationalise
risk appetite
Detailed risk
appetite measures
and limits
High-level
Directional
Specific
Detailed
Figure 3. Strategic plan and risk appetite
A risk appetite framework is good to the extent that it
allows the people who set a firm’s strategy to accept
in a conscious way the risks that correspond with that
strategy and the underlying business model. It’s good
to the extent that people within a firm who take risks
on its behalf know what strategic objectives they are
supporting in their risk-taking; and keep within the
limits translating these objectives. It’s good to the
extent that all of a firm’s material risks are understood,
along with the drivers of those risks. And it’s good
to the extent that risk appetite language as the key
ingredient of its risk culture permeates the firm, its
decision-making processes and the understanding of its
own performance.
The process of setting up a framework can be complex
and time-consuming, and will depend on the nature
and complexity of the firm.
It can be tempting for a firm facing huge amounts of
regulatory and strategic change to take a short-cut
with risk appetite.
Most financial institutions will already have a large
number of limits in place, be they credit, market
or underwriting limits. Faced with pressure to
demonstrate progress on the risk appetite front, it
is relatively easy for a firm to take existing limits and
relabel, rebadge or repackage them for approval by the
Board as a fully-fledged risk appetite framework.
After all, many people think that’s what a risk appetite
framework is, since risk appetite frameworks do contain
a lot of limits. But only if risk limits are the expression
of a firm-wide process of articulation (meshing
top-down direction from the Board with bottom-up
communication of risk insight) will they help to link the
firm’s overall strategic plan with its risk strategy, its risk
management and its actual risk-taking.
If they are not calibrated as part of a shared, firm
specific risk appetite language then individual limits
may be largely irrelevant. A bank may have a €200m
stressed VaR limit for a trading arm, but is that figure
too high or too low given the objectives and strategy
of the firm? What strategic objective is the limit in
question designed to support? And does it relate to
other strategic objectives of the firm? If so, how?
10
The risk strategy relates the firm’s strategic objectives
to its risk management priorities and articulates two
things very clearly: the risks the firm needs to manage
to achieve the strategic plan and the capabilities to
manage those risks.
We would expect both the strategic plan and the
risk strategy to take into account and respond to
the business dimensions as they are relevant to the
firm, e.g. the business model, its operating model,
concentrations and customer profile.
Specific risk objectives can be elaborated, in support
of the overall objectives – based on a well-developed
understanding of how and where risk arises for the
firm. Once the risk capacity of the firm has been
established, the Board can confirm what its appetite is
for particular risks.
This becomes the basis of the high-level risk appetite
statement, used as a key communication tool to set the
tone from the top and guide the behaviour of individual
employees (see ‘Risk appetite in action #4’).
While this may look like a classic example of top-down
control, it is informed by work done by risk managers
throughout the organisation to identify where risks will
arise in the pursuit of its strategy and how they can be
managed. When these risks undergo material change,
so too must the risk appetite statements, so that
they continue to cover the full range of risk (see ‘Risk
appetite in action #5’ overleaf). High-level limits and
triggers are used to monitor whether the risk profile is
within appetite.
One of the benefits of risk
appetite frameworks is that
they help firms understand
where they can afford to
take more risk.
Risk appetite in action #4
The Board meets to approve the firm’s top-level risk appetite statement.
They are aware it will be translated to lower levels of the organisation via
specific limits and want to review those too, to understand the logic and
the review and challenge process. The Directors discuss how their risk
appetite should begin with a linkage to the firm’s mission and business
strategy and the overall risk philosophy. They then review the series of
qualitative and quantitative risk appetite statements. The quantitative
statements have thresholds and are measurable and the qualitative
statements are observable. The statement articulates the desired balance
between the key risk objectives (e.g. target debt ratings, earnings
volatility, capital adequacy) and profitability objectives (Return on Equity
(ROE), Risk Adjusted Return on Capital (RAROC)).
The Chairperson of the Board recalls that the initial SSG observations
on risk management practices during the market turbulence were that
the firms that used multiple measures of risk tended to ‘avoid significant
unexpected losses’ more than those who focused on a single metric or a
few key metrics. The Board therefore makes sure that their risk appetite
statement covers multiple dimensions of risk, and also considers risk
appetite dynamically, under different scenarios or stress cases. They
recognise that the use of stress testing for establishing risk appetite
provides significant value by making risk appetite potentially more
forward looking. For multiple views of risk appetite, risk limits are set for
base case and stress case scenarios.
The firm begins with a desired credit rating (e.g. Moody’s Aa rating) and
breaks it down further into factors that drive the credit rating. For an
Aa rating, the firm would have to remain well capitalised at a desired
confidence level, so it sets appropriate ranges to its capital ratios (Tier 1
Common ratio, Total Capital ratio, Leverage ratio, etc.) under base and
stressed scenarios, and factoring in regulatory expectations. Having
determined the target capital ratio range and given their current capital
structure, the firm translates that into the maximum amount of loss that
it can sustain before breaching the lower end of the range at a desired
confidence level for the desired rating. In the same way, the Directors
review and approve how risk appetite limits and triggers have been
set for its asset quality, funding, and profitability – and that these are
commensurate with its desired credit rating.
Risk appetite frameworks How to spot the genuine article 11
To support the early warning of trends or events that
might move it beyond appetite, the firm needs to
understand the lower-level drivers of those high-level
appetite settings. These are the key risk drivers, which
also need appetite statement to give direction to the firm,
and help cascade the risk appetite down the firm so that
people can relate it to their day-to-day jobs.
Some of these expressions of risk appetite will be specific
and prescriptive: the firm DOES or DOES NOT engage in
certain practices. Others will take the form of detailed
risk measures and set limits that have been chosen and
calibrated for their ability to keep the firm on track. They
will often operate as the ‘levers’ of risk management since
they not only help drive the risk profile but are also the
kinds of things that risk managers could alter to bring the
risk profile within appetite.
A risk appetite framework set up and operating in this
way will further be a proactive defence mechanism but
also a way to spread good risk culture throughout the
firm and improve the quality of risk-reward decisions.
One of the benefits of risk appetite frameworks is that
they help firms understand where they can afford to
take more risk, in a controlled way that supports – not
threatens – their strategic objectives.
Risk culture (D)
Risk appetite
framework Risk governance
(A)
Risk infrastructure
(C)
Risk management
tools (B)
Figure 4. Risk appetite frameworks & other elements of
risk management
Risk appetite in action #5
The Group Compliance Director has been
helping to set his firm’s risk appetite for a
range of risks drivers that are harder than
normal to quantify, stemming as they do
from regulation on treating customers
fairly and anti-money laundering. He has
bought into the concept of risk appetite
as a continuous process of understanding
and judgement that responds to changes
in the business, competitive or control
environments. He sees that the regulatory
authorities are raising the profile of conduct
risk and have set out their approach for a
more intrusive regulatory regime. This seems
to him a clear example of an important
change in the business environment and he
suggests to the CRO that they modify the risk
appetite framework to incorporate conduct
risk. They want to inform the Board of the
control environment around conduct risks
so that it can give top-down direction on its
appetite for this risk.
Risk appetite frameworks in context
As will be clear by now, a risk appetite framework is not
just another risk management tool operated in isolation
by the risk management function. Making risk appetite
work for an organisation implies well-considered
change to four interlocking and mutually reinforcing
elements: the risk appetite framework itself; its risk
governance; the associated risk infrastructure; and its
suite of risk management tools.
However, as illustrated in figure 4 below, central to a
firm’s risk management and governance must be its risk
culture. A firm’s risk management needs to respond to
its business and risk strategy and how it positions itself
in markets. The risk appetite framework provides the
key way to link a firm’s strategy and its management
of risk.
12
To start a new section, hold down the apple+shift keys and click
to release this object and type the section title in the box below.
Once properly integrated, a firm’s risk appetite framework will both support and be supported by: (A) its risk governance; (B) its risk management
tools; (C) its risk infrastructure; and (D) its risk culture. The linkages are explained in more detail below.
How the firm’s risk appetite framework provides support How the firm’s risk appetite framework is supported
A The risk appetite framework and language support risk governance by
providing the Board and senior management with the information and tools
needed to understand and communicate the risks the firm is and should be
taking in line with its risk appetite and its business and risk strategy.
The firm’s risk governance is essential in clarifying lines of accountability
and describing how staff should adhere to the firm’s risk appetite
framework. Implementation and running of the risk appetite framework
depend crucially upon the full buy-in of Board and senior management
and the tone at the top.
B The risk appetite framework provides information to support the efficient
use and development of the firm’s wider risk management tools.
The firm’s wider risk management tools support the risk appetite
framework. For example, running stress tests aligned to the firm’s targeted
future risk profile and its business and risk strategy supports the firm’s
calibration of its risk appetite and limits.
C The firm’s risk infrastructure (including timely aggregation and reporting
of risk data, related systems and processes, and employee skillset) must
respond to and support its current and targeted future risk profile and
its business and risk strategy. The risk appetite framework identifies
comprehensive, firm-wide information necessary to shape the firm’s
risk infrastructure.
A robust and well developed risk infrastructure responding to the firm’s
current and targeted future risk profile and its business and risk strategy
is essential for its risk appetite framework. It is a prerequisite for effective
monitoring, reporting and control of risk appetite, profile and capacity.
D The risk appetite framework and language inform a strengthened
risk culture grounded in the shared value and common practice of
understanding, clearly communicating, and controlling how each
employee’s activities contribute to the firm’s risk profile and the
successful implementation of its strategy.
A firm’s risk culture is in its language and the style and quality of its internal
communication. It is instrumental in the full operational embedding of the
risk appetite framework since only the firm’s risk culture helped by the tone
at the top and appropriate compensation can turn risk appetite statements
and limits into a risk appetite language that is spoken and understood
throughout the firm.
Risk appetite frameworks How to spot the genuine article 13
The Directors and supervisors of a firm need to feel
comfortable that its risks are being managed to a high
standard. To an ever increasing extent, the primary way
to receive assurance will be through confidence that it
has an effective risk appetite framework.
In this section, we suggest some of the ways Directors
(be they Executive or Non-Executive) and regulators can
quickly assess the quality of the risk appetite framework
at a particular firm.
This is all the more important given the relative ease
with which firms can relabel, rebadge and repackage
existing sets of limits as a risk appetite framework.
From the trajectory implied by the regulatory pipeline,
this sort of ‘imitation’ risk appetite framework will not
be good enough.
Genuine risk appetite frameworks should be dynamic,
they should underpin proactive ways of managing risk
and setting and adjusting the firm’s business and risk
strategy and its articulated risk appetite. For this reason,
we suggest that a productive line of questioning is to
look for evidence of the key stages that are essential to
a good risk appetite framework. These have been set
out in figure 2 on page 9, ‘Implementing and running a
risk appetite framework’.
If a risk appetite framework is working well, it should
be straightforward to marshal compelling evidence of
the progression from strategy and objective setting
to the articulation and cascading of risk appetite, the
monitoring and reporting against appetite and control
and control steps – which lead back to the setting of
strategy and objectives.
In addition, there are some common-sense and largely
intuitive questions that can help Directors and supervisors
cut to the chase and decide what sort of risk appetite
framework they have before them. See table 1 below.
4. How to spot a genuine risk
appetite framework
Dimension In genuine risk appetite frameworks In imitation risk appetite frameworks
Breadth
Does it cover all material
risks? Or just the ones
that are easy to measure?
The framework will cover financial and
non-financial risks.
The framework will be weighted towards the
risks that lend themselves to straightforward
quantification but will remain silent on harder
to measure risks.
Depth
Does it integrate topdown
direction with
bottom-up insight?
The Board’s risk appetite statement cascades
down the firm and is translated into further risk
statements around the risk drivers that make it
easier to relate the overall appetite to the day
jobs of people lower down the firm.
There may be a bland risk appetite statement
but it is so generic that it can hardly be said to
shape, guide or constrain behaviour.
Language and culture
Do staff use risk appetite
concepts in their day
jobs? Can they answer
questions on how these
concepts relate to them?
If you take front office employees and ask
them what they think of the firm’s risk appetite
and how it applies to them, you will receive
cogent responses.
Nobody outside the risk function will be able
to tell you what risk appetite means or how it
applies to their role.
Sponsorship
Are the CEO, CFO or
CRO active champions of
risk appetite?
Senior executives can explain how and
why they have gone about trying to embed
risk appetite.
Senior executives pay lip service to the
concepts, but fail to push them through.
Decision making
Can the Board or
Executive give an example
of the last time that
risk appetite informed
a business decision?
The Board and Executive can give examples
of decisions that have been influenced by risk
appetite; business risk owners can explain
what risk objective they were supporting when
they set particular bottom-up limits.
The Board and Executive will struggle to give
a coherent answer; business owners will not
be able to link their calibration of limits and
triggers to specific risk or business objectives.
Remuneration
Is the firm using risk
appetite within its reward
and remuneration plans?
Employees will be incentivised to help deliver
a strong risk appetite culture and to remain
within agreed risk appetite limits.
Some employees may be incentivised to remain
within specific risk appetite limits, but coverage
is patchy and in any case, the limits in question
have weak linkages to firm-wide objectives.
Table 1: Questions to help spot a genuine risk appetite framework
14
To start a new section, hold down the apple+shift keys and click
to release this object and type the section title in the box below.
5. How risk appetite might look in
three to five years’ time
Following our review of regulatory pronouncements,
policy papers, speeches and both draft and actual
regulation, we suggest that risk appetite may well
become the primary lens through which the quality
of a firm’s risk management, governance and culture
is assessed.
The FSB, the Basel Committee on Banking Supervision
(BCBS), the SSG and the International Association
of Insurance Supervisors (IAIS) have each woven
the concepts of risk appetite into their thinking
on supervision.
National and international regulators are pulling in the
same direction.
From capital planning to data quality, from governance
to strategy, remuneration to public disclosure, the
applications for risk appetite are far and wide. Firms
should expect to be judged on the strength of their
risk appetite framework. Executive and Non-Executive
Directors should be preparing for the heightened
prominence of risk appetite.
The direction of travel by supervisors and regulators is
obvious, the implied destination is clear.
Direction of travel by regulators Implied destination
FSB’s Example of a Risk Governance Framework:
Board “approves and oversees the firm’s risk appetite framework, including: the risk appetite
statement (RAS), risk limits by business units consistent with the RAS, and policies and processes to
implement the risk management framework” 2013
BCBS:
“Boards [should] set a suitable risk appetite to define the level of risk the banks are willing to assume or
tolerate… [and should ensure that] senior management take the steps necessary to monitor and control
all material risks consistent with the approved strategies and risk appetite.” 2012
APRA:
“The Board must establish the risk appetite of the APRA-regulated institution. The institution must
maintain an appropriate, clear and concise risk appetite statement that addresses its material risks.
The Board must approve the risk appetite statement.” 2013
European Banking Association (EBA):
“An institution shall develop an integrated and institution-wide risk culture, based on a full
understanding of the risks it faces and how they are managed, taking into account its risk
tolerance/appetite” 2011
ASIC:
The Board can ensure that the organisation’s reward and remuneration structure is aligned with and
supportive of the responsible entity’s risk management systems. 2013
1. Governance: Firms are run based upon
their risk appetite framework.
The governance of the firm is that of its
risk appetite framework. It provides board
and senior management with the
information, the tools and the risk
appetite language needed to understand
and communicate from the top to the
firm’s shop floor and across all business
and control areas the risks the firm is and
should be taking in line with its business
and risk strategy.
IAIS:
The insurer’s Board should “set and oversee the implementation of the insurer’s business objectives and
strategies for achieving those objectives, including its risk strategy and risk appetite, in line with the
insurer’s long term interests and viability” 2011 (amended 2012)
UK Prudential Regulation Authority (PRA):
“the PRA expects a firm’s risk appetite to be integral to its strategy and the foundation of its risk
management framework, so that the whole firm operates within this appetite.” 2013
APRA:
“To be rated ‘low risk’ on risk governance, a board would need to demonstrate, inter alia, that it is
providing clear direction and leadership for the institution, evidenced in a clearly articulated risk appetite
statement, risk management strategy and overall business strategy” 2013
FSB:
“important signals of a sound risk culture … are that problems are recognised and escalated as
appropriate, the financial institution’s risk tolerance is clearly communicated, and controls and
incentives exist for the financial institution’s risk profile to remain within desired boundaries” 2012
2. Strategy: It becomes standard industry
practice to develop the firm’s business and
risk strategies based upon the view its risk
appetite framework conveys on the firm’s
risk profile within the broader context of
its competitive position in an evolving
market and risk environment
3. Culture: Risk appetite framework and
language inform the firm’s risk culture
grounded in the shared value and common
practice of understanding, clearly
communicating, and controlling how each
employee’s activities contribute to the
firm’s risk profile and the successful
implementation of its business and risk
strategy. And everyone in the firm can
explain that.
Risk appetite frameworks How to spot the genuine article 15
To start a new section, hold down the apple+shift keys and click
to release this object and type the section title in the box below.
Direction of travel by regulators Implied destination
Revision of the EU Capital Requirements Directive (CRD IV):
“remuneration policies should be aligned with the risk appetite, values and long-term interests of the
credit institution or investment firm” 2013
Canadian Office of the Superintendent of Financial Institutions (OFSI):
Risk appetite statements should be “linked to the firm’s short-term and long-term strategic, capital and
financial plans, as well as compensation programs” 2013
APRA:
“A prudent overall remuneration structure, including the balance and selection of components of
remuneration, would promote a culture and working environment that attract and encourage staff who fit
a regulated institution’s risk appetite.” 2009  
Canadian Office of the Superintendent of Financial Institutions (OFSI):
The Board should review and discuss the FRTI’s (federally-regulated financial institution) “business and
financial performance relative to the Board-approved strategy and Risk Appetite Framework” 2013
APRA:
“APRA expects a RSE licensee’s risk management framework would ensure that the Board receives regular
reporting on material risks relative to the RSE licensee’s risk appetite statement, assessment of risks and
the operation and effectiveness of controls.” 2013
4. Remuneration: Incentives plans are
explicitly structured to support the firm’s
risk appetite and the taking and
controlling of risks in line with its risk
appetite framework.
SSG:
“A common risk appetite language across the firm, expressed through qualitative statements and
appropriately selected risk metrics, facilitates the acceptance and effective monitoring of the
[risk appetite framework]” 2010
APRA:
It is one thing to have a risk appetite. It is another to express it clearly and unambiguously in a risk
appetite statement (RAS) in a way that generates a common understanding and a consistency in risk
management across the business. 2012
BCBS:
“Risk data and reports should provide management with the ability to monitor and track risks relative
to risk tolerance/appetite” 2013
BCBS:
Banks should “disclose key points concerning [their] risk tolerance/appetite… with a description of the
process for defining it and information concerning the board involvement in such process” 2010
APRA:
“APRA recognises that an RSE licensee may produce an appropriate summary of the pertinent parts of its risk
appetite statement to reflect the audience and any confidential or commercially sensitive information.” 2013
UK FSA:
As part of the Firm Systematic Framework, the FCA will “assess how effectively a firm identifies,
manages and reduces conduct risks” 2012
5. Language: From start to end of risk
taking and controlling and up and down
the firm, risk appetite is the common
language spoken to articulate, communicate
and debate risk.
FSB:
Risk appetite frameworks are at an early stage of development when coverage does not “extend to all
relevant subsidiaries in the framework” or include “all the material risks the firm faces, particularly
reputational and operational risks” 2013
German Federal Financial Supervisory Authority (BaFin) (Translated):
"Senior management has to define a risk strategy that is consistent with the business strategy and the
resulting risks. The risk strategy… has to define the risk management objectives for key business activities
as well as the means to achieve these objectives. In particular, risk tolerances have to be set for all
material risks taking into account risk concentrations." 2012
APRA:
“APRA expects that the risk appetite and risk management framework of a regulated institution will address
all material sources of risk for that institution. This will include risks that are covered by specific regulatory
capital requirements and risks that are not, regardless of whether those risks are able to be quantified.” 2013
7. Scope: The risk appetite framework
covers all relevant risks including the
non-financial ones. Its scope is regularly
reassessed and adjusted as appropriate to
ensure that coverage of the firm’s evolving
risk profile remains complete.
8. Disclosure: Internal communication
based upon the firm’s risk appetite
language and external communication are
aligned. Firms publish their high-level Risk
Appetite Statement (as agreed by the
Board) and structure their external
disclosures to show how this high-level
statement translates into the management
o