---
title: OCC CC
author: jake
date: '2018-06-13'
slug: occ-cc
categories:
  - credit cards
tags: []
---


The credit card is one of the most universally accepted and convenient payment methods,
used by millions of consumers and merchants worldwide as a routine means of payment for a
variety of products and services. The rapid growth of the credit card industry indicates the
card’s value to the financial community, which includes consumers, merchants, and issuing
banks.
Because of their profitability, credit cards play a role in the strategic plans of many banks,
which may function as issuers, merchant acquirers, or agent banks. There are several major
issuers, very few of them community banks. Community banks that issue cards do so mainly
as a service to their existing customer bases. Issuing banks hold or sell credit card loans and,
therefore, bear some credit risk.
A merchant bank or acquiring bank is an entity that has entered into an agreement with a
merchant to accept deposits generated by credit card transactions. Processing merchant sales
drafts may result in customer chargebacks and, therefore, create some transaction risk to the
merchant bank. For more information, refer to the “Merchant Processing” booklet of the
Comptroller’s Handbook.
An agent bank is a bank that has entered into an agreement to participate in another bank’s
card program, usually by turning over its applicants for credit cards to the bank administering
the program and by acting as a depository for merchants.
This “Credit Card Lending” booklet discusses the operations of issuing banks and provides
information for examiners regarding the types of elements usually found in systems
maintained by prudent bankers. Specific items identified for inclusion in bank policies,
procedures, and guidelines are not presented as a required checklist because each bank and
its systems vary. Examiners should consider the circumstances of the individual bank to
determine essential system elements.
The Truth in Lending Act (TILA) of 1968 (15 USC 1601 et seq.) was implemented by
Regulation Z (12 CFR 1026) and became effective on July 1, 1969, and has since been
amended many times. In 2009, Congress passed the Credit Card Accountability
Responsibility and Disclosure Act (CARD Act), which further amended TILA. The CARD 
Version 1.2 Introduction > Overview
Comptroller’s Handbook 2 Credit Card Lending
Act provisions required creditors to increase the amount of notice consumers receive before
the rate on a credit card account is increased or a significant change is made to the account’s
terms. The amendments allowed consumers to reject such increases and changes by
informing the creditor before the increase or change takes effect. The CARD Act provisions
also involved rules regarding interest rate increases, over-limit transactions, and student
cards. Lastly, they addressed the reasonableness and proportionality of penalty fees and
charges and the reevaluation of rate increases. Accordingly, throughout this booklet, there are
references to the CARD Act. For more information about CARD Act requirements and
examination procedures, refer to the “Truth in Lending Act” booklet of the Comptroller’s
Handbook.
The Home Owners’ Loan Act of 1933 (HOLA) (12 USC 1461 et seq.), established the
lending and investment limitation of FSAs. The statute is implemented by 12 CFR 160.
Although FSAs are generally limited under 12 USC 1464(c)(2)(D) to investing 35 percent of
assets in consumer loans and certain securities, section 5(c)(1)(T) of HOLA
(12 USC 1464(c)(1)(T)) authorizes FSAs to invest in credit cards and loans made through
credit card accounts without a statutory percentage of assets limitation. HOLA’s credit card
lending authorization is separate from, and in addition to, the investment limits for other
loans and investments authorized under HOLA. FSAs do not have to aggregate their
consumer-related credit cards with other consumer loans in determining compliance with the
limitations on consumer loans and certain other assets in section 5(c)(2)(D) of HOLA
(12 USC 1464(c)(2)(D)). Similarly, FSAs do not have to aggregate business-related credit
card accounts with loans made under HOLA’s commercial loan authority.
Regulations and statutes applicable to national banks and FSAs are discussed throughout this
booklet. Further, this booklet contains numerous references to appendix A, “Transaction
Testing.” Transaction testing is one of the most important steps in the examination process
for credit card lending because account-level testing allows examiners to determine exactly
what processes the bank is using and then assess those processes. Transaction testing also
indicates the bank’s level of adherence to its own policies and formal procedures as well as to
OCC guidance.
The dynamics of the credit card market require the successful issuing bank to manage every
aspect of the lending process. Every step in the lending function, consistent with consumer
compliance, is crucial to maximizing profits in this competitive environment, with rapidly
changing products, terms, and technologies. This booklet discusses each segment of an
issuing bank’s credit card operation, from marketing and account acquisition to account
management and collections.
Competition, market saturation, and changing consumer demographics and attitudes have
forced successful issuing banks to be innovative with the credit card products they offer, their
customer selection, and management methods. This booklet discusses various types of credit
card programs, such as affinity and cobranded cards, and the unique characteristics, risks,
and controls necessary for each. This booklet also includes a discussion of credit scoring,
because all major issuers use this technology to help identify possible customers and then
manage cardholder accounts.
Version 1.2 Introduction > Overview
Comptroller’s Handbook 3 Credit Card Lending
Banks also use securitization as a funding source for credit card lending. This provides banks
some flexibility with respect to availability and cost of funding for the portfolios. Banks
should ensure that these securitizations are accounted for in accordance with Accounting
Standards Codification (ASC) 810, “Consolidation,” and ASC 860, “Transfers and
Servicing,” which generally do not allow for derecognition of the card receivables in most
traditional credit card securitization structures. For more information, refer to the “Asset
Securitization” booklet of the Comptroller’s Handbook.
Several factors have caused the credit card business to become one of the most complex and
competitive areas in the financial services industry. The market environment, through everevolving
technology, has become one of speed and volume. Due to the inherently significant
credit and operational risks, issuing banks should have written operating policies tied to welldesigned
business plans and risk management systems.
Generally, banks that offer credit cards to their own customers or stay within their local
market area present less risk than institutions that market their credit card program outside
the local area. Community banks have difficulty competing successfully with national issuers
that have more expertise, technology, and economies of scale.
Credit Card Products
Credit card products generally fall into the following broad categories:
• General purpose cards (including charge cards).
• Proprietary or private-label cards.
• Corporate or commercial cards.
• Secured cards.
General Purpose Cards
General purpose bank cards, including affinity and cobranded cards, are branded credit cards
that are accepted by a wide variety of merchants and service providers. Banks that offer
general purpose cards are typically members of Visa or MasterCard, the two primary systems
for the settlement of interbank credit card transactions. Issuers may offer a “charge” card (on
which the balance must be paid in full each month) and a “credit” card where (the balance
can revolve month-over-month). Bank cards generate transaction-based interchange income
(generally a small percentage of each transaction to compensate the bank for processing the
transaction) in addition to finance charge and fee-related income.
Issuers of general purpose cards may form partnerships with businesses, associations, and
not-for-profit groups to market their credit cards. These credit cards, called affinity or
cobranded cards, are typically issued as MasterCard, Visa, or American Express cards. The
cards normally carry the affinity group or cobranding partner’s name and logo. These cards
can be used for purchases anywhere the applicable processing network (e.g., Visa,
MasterCard) is used and can sometimes be used for purchases of a partner’s products and
services. A bank issues the card under a contractual agreement with a partner. Although 
Version 1.2 Introduction > Overview
Comptroller’s Handbook 4 Credit Card Lending
compensation arrangements can vary, the partner typically endorses the bank’s card in return
for negotiated financial compensation based on customer acceptance and use of the card.
Although the terms “cobranded” and “affinity” are sometimes used interchangeably, there are
differences. Generally, affinity cards are issued for a variety of groups and not-for-profit
organizations, such as alumni associations, professional organizations, and sports enthusiasts.
The cards provide cardholders with access to credit and a way to identify with the group. The
affinity group is compensated for endorsing the issuer’s card. Compensation can include a
portion of annual credit card fees, fees paid on renewal, a percentage of the interchange
income, or a share of the interest income. This arrangement provides groups with a relatively
low-cost source of income. The issuing bank expects to benefit from the affinity group’s
endorsement; while the affinity group introduces the bank to what the bank hopes are highquality
and loyal customers. Members of affinity groups also may be more responsive to
credit card solicitations than consumers are to generic cards, providing the issuer with more
effective target marketing initiatives.
In cobranded card programs, the issuing bank forms partnerships with for-profit
organizations, such as retailers, hotels, gasoline companies, automobile manufacturers, and
airlines. The cobranding partner may receive part of the income that would normally go to
the issuer, such as interchange income, or may receive other compensation based on the
volume or activity of accounts opened through the card partnership. The cobranding partner
may also agree to share in a portion of credit losses or other expenses associated with the
card receivables. The partner is willing to share various income and expenses with the card
issuer because the issuer brings customer service and expertise in consumer lending to the
partnership. A bank card issuer generally benefits from a cobranding program through
increased credit card receivables.
General purpose cards, including affinity and cobranded cards, often offer rewards programs
as an incentive for cardholders to use a specific card. For cobranded and affinity cards, the
nonbank partner offers financial rewards, such as discounts tied to the partner’s product,
points, or even some percentage of cash back. Recently, these types of programs have been
adopted by other general purpose cards, although the rewards they offer are not tied to a
specific entity. (Refer to the “Reserving for Rebate Programs” section in the “Risk
Management” section of this booklet for a discussion of risks associated with rebates.)
Issuing banks should not materially alter underwriting standards, account management
activities, or collection practices that are important to safety and soundness simply to
accommodate prospective affinity or cobranded card customers. Examiners should review
and discuss with bank management any modifications to terms, account management
activities, or collection practices to determine that any impact to portfolio quality does not
serve as the basis for a safety and soundness concern or compliance risk.
Issuing banks with numerous partnership program accounts tied to affinity or cobranded
programs can be seriously affected by partners’ viability and commitment to the program.
Bank management should thoroughly analyze potential credit card lending partners before
finalizing contracts. Negative publicity about the partner could reflect poorly on the bank. 
Version 1.2 Introduction > Overview
Comptroller’s Handbook 5 Credit Card Lending
Issuers of affinity cards should obtain verification from an independent source that a
potential partner is legitimate. Bank management should determine and monitor the financial
status of its cobranding partners, because the bank might be exposed to liability for unpaid
rebates if the partner is not financially sound.
Contract terms should specify that control over the partnership program rests with the issuer.1
Issuers should track and monitor each partnership program, and should pay particular
attention to aspects of the program such as response and approval rates, utilization rates,
purchase volume, delinquencies, and charge-offs. The bank’s planning strategies should
consider the possibility of high attrition rates if a partner withdraws its endorsement from the
bank. The bank should periodically assess the profitability of each relationship to ensure that
it is financially feasible to continue offering the cobranded or affinity card. Although the
product may be profitable initially, the issuing bank may find that the contract is no longer
profitable as circumstances change.
Proprietary or Private-Label Cards
Proprietary or private-label cards are generally accepted at only one retailer to facilitate the
purchase of that particular retailer’s goods and services. In addition to traditional retailers,
many sellers of high-cost goods (such as furniture, kitchen appliances, etc.) often offer their
own credit cards.
Proprietary or private-label card agreements may include various revenue and expensesharing
arrangements as described in the section above. One additional feature commonly
associated with private-label cards, particularly for retailers of high-cost goods, is the
promotional period. Such programs often allow the consumer a period of no interest on
purchases they make from the retailer. Examples of this type of offer appear in
advertisements for various consumer goods from furniture stores offering “No Interest for
Two Years” on purchases made by a certain date.2 These programs can be structured in two
ways: (1) interest accrues during the promotional period, and, if the balance is not paid in full
 1 Refer to OCC Bulletin 2013-29, “Third-Party Relationships: Risk Management Guidance” (October 30, 2013),
which sets forth regulatory guidance for third-party relationships.
2 Issuers should be sure that any solicitations, application, account-opening materials, or other disclosures
comply with Regulation Z and do not violate section 5 of the Federal Trade Commission Act (FTC Act), which
prohibits unfair or deceptive acts or practices (UDAP), or section 1036(a)(1) of the Dodd–Frank Wall Street
Reform and Consumer Protection Act (Dodd–Frank Act), 12 USC 5536(a), which prohibits unfair, deceptive, or
abusive acts or practices (UDAAP). Marketing materials for promotional annual percentage rate (APR)
programs may risk being deceptive if they do not clearly and prominently describe the material costs,
conditions, and limitation of such offers and the effect of promotional APR offers on the grace period for new
purchases. The Consumer Financial Protection Bureau (CFPB) has issued a bulletin advising credit card issuers
of the risks associated with the marketing of credit card promotional offers. Refer to CFPB Bulletin 2014-2,
“Marketing of Credit Card Promotional APR Offers.”
Version 1.2 Introduction > Overview
Comptroller’s Handbook 6 Credit Card Lending
when the promotion expires, it is added to the outstanding balance at the end of the period;3
or (2) no interest accrues during the promotional period, but interest begins to accrue if the
balance is not paid in full when the promotional period expires.4
Promotional programs should not, however, defer principal payments or have a deferred
payment option, which features a period during which no payments are required of the
consumer. Minimum monthly payments that amortize the current balance over a reasonable
period of time are a key tenet of safe and sound retail lending. Regular monthly payments
add structure and discipline to the lending arrangement, provide regular and ongoing contact
with the borrower, and allow the borrower to demonstrate, and the bank to assess, continued
willingness and ability to repay the obligation over time. Conversely, the absence of a regular
payment stream may result in protracted repayment and mask true portfolio performance and
quality.
Corporate or Commercial Cards
Corporate or commercial charge cards are usually issued to facilitate corporate or
government travel and entertainment (T&E) or procurement. Some banks also issue
consumer charge cards. Generally, the balance is due in full at the end of each billing cycle.
Although T&E cards are typically general purpose in nature, procurement cards may be
either general purpose or proprietary. Corporate cards are generally less profitable to banks
than consumer credit cards because users of corporate cards normally do not incur finance
charges. Rather, annual fees, interchange income, and other service fees are the primary
sources of income for banks that issue these cards. As a result, banks should closely analyze
the costs and risks associated with these programs and have the necessary expertise in place
before engaging in this type of business. Corporate and commercial cards are subject to the
same regulatory guidance as consumer cards with respect to safety and soundness issues.
Secured Cards
Secured cards look and function like traditional, unsecured credit cards, but the credit
extended by the issuer is partly or wholly secured by borrower collateral, typically in the
form of a bank deposit. These cards are generally marketed to individuals with limited or
blemished credit histories, who may not be eligible for unsecured credit. The cards may serve
 3 Under this program structure, accrued interest can be imposed only if the specified period is six months or
longer and, before the commencement of the promotional period, the issuer discloses in a clear and conspicuous
manner the length of the period and the rate at which interest will accrue. Refer to 12 CFR 1026.55(b)(1).
4 Assuming the issuer promotes such a waiver, the cessation of the waiver if the balance is not paid in full at the
end of the promotional period constitutes an increase in the APR for the purposes of Regulation Z. Refer to
12 CFR 1026.55(e). Such an increase is permissible under 12 CFR 1026.55(b)(1) if the promotional period is
six months or longer and, before the beginning of the promotional period, the card issuer clearly disclosed the
length of the period and the APR that would apply after the period ended.
Version 1.2 Introduction > Risks Associated With Credit Card Lending
Comptroller’s Handbook 7 Credit Card Lending
as a means for those individuals to establish or improve their credit and to qualify for or
“graduate” to more traditional unsecured credit.5
In a traditional secured card program, funds are transferred to the issuing bank by the
consumer at account opening, pledged as security for the credit card account, and placed on
deposit (at the issuer or another depository institution) in the name of or for the benefit of the
consumer. The consumer generally may not access those funds. Rather, the funds remain on
deposit so that if the consumer defaults on his or her credit card account, the deposited funds
may be used to help satisfy the debt. Minimum bank deposits under secured credit card
programs typically range from $100 to $500, although customers are often permitted to
deposit more if they choose. The deposit account may earn interest, depending on the terms
of the agreement. In secured card programs, it is imperative that issuing banks have strong
controls in place to ensure that the collateral is not unintentionally released.
In some programs, security deposits and account opening fees are charged to the credit card
account. The CARD Act and Regulation Z limit fees issuers can charge before account
opening and during the first 12 months after account opening. For more information, refer to
the “Truth in Lending Act” booklet of the Comptroller’s Handbook.
Risks Associated With Credit Card Lending
From a supervisory perspective, risk is the potential that events will have an adverse effect on
a bank’s current or projected financial condition6 and resilience.
7 The OCC has defined eight
categories of risk for bank supervision purposes: credit, interest rate, liquidity, price,
operational, compliance, strategic, and reputation. These categories are not mutually
exclusive. Any product or service may expose a bank to multiple risks. Risks also may be
interdependent and may be positively or negatively correlated. Examiners should be aware of
this interdependence and assess the effect in a consistent and inclusive manner. Examiners
also should be alert to concentrations that can significantly elevate risk. Concentrations can
accumulate within and across products, business lines, geographic areas, countries, and legal
entities.
The primary risks associated with credit card lending are credit, operational, liquidity,
strategic, reputation, interest rate, and compliance. These are discussed more fully in the
following paragraphs. Although all of these risks are embedded in credit card lending, the
primary focus of this booklet is credit risk, with some emphasis on operational, strategic, and
reputation risk.
 5 Cards that are marketed as improving credit must have clear explanations to consumers to ensure these
products and their marketing do not constitute a UDAP or UDAAP.
6 Financial condition includes impacts from diminished capital and liquidity. Capital in this context includes
potential impacts from reduced earnings and market value of equity.
7 Resilience recognizes the bank’s ability to withstand periods of stress.
Version 1.2 Introduction > Risks Associated With Credit Card Lending
Comptroller’s Handbook 8 Credit Card Lending
Credit Risk
Credit risk poses the most significant risk to banks involved in credit card lending. Because
credit card debt is generally unsecured, repayment depends primarily on a borrower’s
willingness and capacity to repay. The highly competitive environment for credit card
lending provides consumers with ample opportunity to hold several credit cards from
different issuers and to pay only minimum monthly payments on outstanding balances. In
such an environment, borrowers may become overextended and unable to repay, particularly
in times of an economic downturn or a personal catastrophic event.
Regulation Z prohibits a card issuer from opening a credit card account for a consumer under
an open-end (not home-secured) consumer credit plan, or increasing any credit limit
applicable to such account, unless the card issuer considers the consumer’s ability to make
the required minimum periodic payments under the terms of the account, based on the
consumer’s income or assets and current obligations.8
Product pricing may vary widely and include both fixed- and variable-rate structures. Issuers
may offer low introductory rates to consumers to entice them to transfer balances to a new
credit card. Introductory rate offers may be as low as zero percent, although transfer fees may
apply. At the end of the introductory period, the variable rate is likely to increase.9 For more
information on interest rate limitations and requirements imposed by the CARD Act, refer to
the “Truth in Lending Act” booklet of the Comptroller’s Handbook.
In addition to credit risk posed by individual borrowers, credit risk exists in the overall credit
card portfolio. Relaxed underwriting standards, aggressive solicitation programs, inadequate
account management, and a general deterioration of economic conditions can increase credit
risk. Changes in product mix and the degree to which the portfolio has concentrations,
geographic or otherwise, can also affect a portfolio’s risk profile.
Banks control credit risk through coordinated strategic and marketing plans. Banks should
have comprehensive policies and procedures that include strong front-end controls over
underwriting standards, well-defined account management processes, strong back-end
controls for effective collection programs, and robust monitoring and reporting management
information systems (MIS).
Examiners assess credit risk by evaluating portfolio performance, profitability, and borrower
characteristics by business lines, products, and markets. They consider changes in
underwriting standards, account acquisition channels, credit scoring systems, and marketing
plans.
 8 Refer to 12 CFR 1026.51.
9 For information on Regulation Z requirements pertaining to introductory rates, refer to 12 CFR 1026.55(b)(1).
Version 1.2 Introduction > Risks Associated With Credit Card Lending
Comptroller’s Handbook 9 Credit Card Lending
Operational Risk
A bank’s success in credit card lending depends in part on achieving economies of scale.
Credit card operations are highly automated, service large volumes of transactions, and
require strong operational controls. Aggressive growth has the potential to stretch operational
capacity and can cause problems in handling customer accounts and in processing payments.
Fraud is a continuing problem associated with credit card programs. The very nature of the
product—an easily obtainable unsecured line of credit that is basically managed by the
customer—makes it an ideal mechanism for fraud. A bank’s technology platform can pose
significant operational risk to an issuer. Platforms that are outdated or difficult to use or
reprogram expose banks to higher servicing costs and higher potential for errors when they
require manual workarounds or manual intervention.
With most requirements under TILA pertaining to credit cards, a creditor that fails to comply
generally may be held liable to the consumer for actual damages and legal costs.10 In
addition, a creditor may be held liable for twice the amount of the finance charge involved,
subject to certain limits. Effective controls and efficient processes should be in place to
manage litigation exposure in credit card lending. Operational risk exists not only in account
originations and servicing, but also in collections, whether or not a bank uses external
vendors or attorneys in collection practices. There are many detailed legal requirements
around the preparation and filing of collection documentation, and each issuer should have
processes in place, or ensure that its vendors have processes in place, to ensure compliance
with those requirements.
To control operational risk, a bank should maintain effective internal controls, internal and
third-party audits, third-party relationship management practices, business continuity
planning, and MIS. Bank management should consider the volume of accounts managed
(both on the books and securitized), the capabilities of systems and technologies in relation to
current and prospective volume, contingency preparedness, and exposures through the
payment system. If a bank employs vendors in any part of its operations, the bank should
have strong third-party relationship management practices. OCC Bulletin 2013-29, “ThirdParty
Relationships: Risk Management Guidance,” provides guidance to banks for assessing
and managing risks associated with third-party relationships.
Examiners assess operational risk by evaluating the adequacy of systems and controls
governing credit card application processing, account management, and collections.
 10 TILA exempts a creditor from civil liability for a violation if the creditor shows by a preponderance of the
evidence that the violation was not intentional and results from a bona fide error, notwithstanding the
maintenance of procedures designed to avoid such an error. Refer to 15 USC 1640(c). Further, failing to comply
with the advertising provisions in 15 USC 1661–1665b does not expose a creditor to civil liability for actual
damages or legal costs. 
Version 1.2 Introduction > Risks Associated With Credit Card Lending
Comptroller’s Handbook 10 Credit Card Lending
Liquidity Risk
Banks use a variety of funding techniques to support credit card portfolios. Techniques
employed by individual banks introduce different types of liquidity risk. For example, a
credit card bank that is self-funded through securitizations (refer to the “Glossary” section of
this booklet) has different liquidity risk considerations than a credit card bank that is funded
by its retail parent’s commercial paper. Moreover, large banks with access to a full array of
funding sources to support credit card operations have different liquidity risk considerations
than smaller institutions with potentially less diverse funding sources.
Liquidity risk is present in a bank’s obligation to fund unused credit card commitments. For
example, more consumers use their cards at certain times, such as around holidays, so banks
should be aware of seasonal demands.
Credit card portfolios composed of higher-risk assets and having unusual portfolio volatility
may be difficult to securitize or sell. Failure to adequately underwrite or collect loans may
trigger early amortization of a securitization, which could cause liquidity problems, increase
costs, or limit access to funding markets in the future. For more information on early
amortization of securitizations, refer to the “Asset Securitization” booklet of the
Comptroller’s Handbook.
Banks may control liquidity risk through a strong balance sheet management process, a
diversified funding base, a comprehensive liquidity contingency plan, and laddered
securitization maturities, if appropriate.
To assess liquidity risk, examiners consider
• reliability of funding mechanisms.
• dependence of the credit card operation on securitization of assets.
• volume of unfunded commitments.
• attrition of credit card accounts.
• stability of affinity and cobranded card relationships.
• ability to fund seasonal increases in demand.
Strategic Risk
Strategic risk in credit card lending can arise when business decisions adversely affect the
quantity or quality of products and services offered, program operating controls, management
supervision, or technology. Bank management’s knowledge of economic dynamics and
industry market conditions can help limit strategic risk. For example, banks may be exposed
to strategic risk if they inadequately plan for marketing of preapproved credit card
solicitation programs. To mitigate the risk, bank management should fully test new markets,
analyze results, and refine solicitation offers to limit the booking of new credit card accounts
that do not perform as anticipated.
Version 1.2 Introduction > Risks Associated With Credit Card Lending
Comptroller’s Handbook 11 Credit Card Lending
Failure to sufficiently test new markets and strategies before full rollout can present
significant strategic risk to a bank. For example, an issuer that wants to change the
composition of its portfolio to be more heavily weighted toward a certain demographic or
customer base may minimize strategic risk by testing the new strategy in a pilot phase.
Similarly, to effectively manage the risk of enabling credit cards with EMV (Europay,
MasterCard, and Visa) integrated circuit card credit card technology (IC cards or chip cards),
bank management should provide for adequate testing and thoroughly consider the costs and
benefits of the new technology before introducing it. Bank management should pay particular
attention to changes in the credit card marketplace, such as the increased use of chip cards or
MasterCard and Visa implementing a fraud liability shift for point-of-sale transactions that
provides incentives for banks and merchants in the United States to shift from a signaturebased
model to a chip and PIN-based model.
Examiners assess strategic risk by determining whether bank management has evaluated the
feasibility and profitability of each new credit card product and service before it is offered.
Examiners determine whether the bank’s pricing, growth, and acquisition strategies
realistically consider economic and market factors. In particular, examiners evaluate whether
a proper balance exists between the bank’s willingness to accept risk and its supporting
resources and controls.
Reputation Risk
A bank’s credit card operation can create reputation risk in a variety of ways. For example,
poor servicing of existing accounts, such as failing to appropriately resolve consumer issues
or process payments in a timely manner, can result in the loss of existing relationships.
Issuing banks that employ outside vendors to perform solicitation, servicing, collection, or
other functions should effectively monitor and control the products and services provided by
the third parties. Reputation risk also may exist when a bank offers cobranded or affinity
credit cards, because consumers may associate the quality of the bank’s partner’s products
and services with the bank.
Certain credit card practices can also increase reputation risk. To illustrate, common industry
practices, such as punitive and penalty pricing for defaults on accounts, are perceived as
unfriendly to the consumer. Several major issuers have received negative publicity for having
employed these practices.
To assess reputation risk, examiners consider
• volume and number of credit card accounts under management or administration.
• merger and acquisition plans and opportunities.
• potential or planned entrance into new credit card products, marketing strategies, or
technologies (including new delivery channels).
• the market’s or public’s perception of the bank’s financial stability.
• past performance in offering new credit card products and services and in conducting due
diligence.
Version 1.2 Introduction > Risks Associated With Credit Card Lending
Comptroller’s Handbook 12 Credit Card Lending
• ability to prevent violations of laws and regulations and minimize impact from any
violations that do occur.
• volume of customer complaints and the ability to address them.
• management’s willingness and ability to adjust strategies based on regulatory changes,
market disruptions, or market or public perception.
• quality and integrity of MIS and the development of expanded or newly integrated
systems.
Interest Rate Risk
Interest income and fee income derived from credit card portfolios are sensitive to changes in
interest rates. Complex, illiquid hedging strategies or products have their own risks that may
exacerbate interest rate risk. The availability of a wide variety of rate structures for credit
card products provides flexibility in managing such risk. Banks should manage interest rate
risk on a consolidated basis for their credit card portfolios, as well as within individual
product lines.
When assessing interest rate risk, examiners should consider the CARD Act’s limits on rate
increases,11 as well as the variety of pricing programs and the impact of competition on rates.
Intense competition on pricing to meet market demands can compress margins. Examiners
should also consider the source(s) and cost of funding the credit card portfolio.
Compliance Risk
The evaluation of compliance risk should consider the numerous laws that affect aspects of
credit card lending. These compliance laws include: the Bank Secrecy Act of 1970 (BSA)
and consumer laws and regulations, including TILA, the Fair Credit Reporting Act of 1970
(FCRA), the Fair Debt Collection Practices Act of 1977 (FDCPA), the CARD Act, the Equal
Credit Opportunity Act (ECOA), the Servicemembers Civil Relief Act of 2003 (SCRA), and
laws prohibiting UDAP and UDAAP.12 Bank management should ensure that staff and thirdparty
service providers involved in marketing, credit scoring, processing applications, and
collection activity comply fully with these laws and regulations. The examiner should
determine whether the bank’s credit card lending activities treat customers fairly and fulfill
the bank’s contractual obligations with the customer.
Examiners must understand the BSA risks surrounding the institution and its third-party
relationships. Secured credit cards may pose a higher risk of money laundering or terrorist
financing, and examiners should assess the potential risks from the following: (1) placement
(introducing cash into the financial system by some means); (2) layering (undertaking
complex financial transactions to camouflage the illegal source); and (3) integration
 11 Refer to 12 CFR 1026.55.
12 See footnote 2.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 13 Credit Card Lending
(generating wealth from the placement of the illicit funds). Examiners must also understand
each credit card program as it relates to the BSA.
Refer to the Federal Financial Institutions Examination Council’s FFIEC Bank Secrecy
Act/Anti-Money Laundering Examination Manual and the “Fair Credit Reporting,” “Fair
Lending,” “Truth in Lending Act,” and other Consumer Compliance series booklets of the
Comptroller’s Handbook for the primary compliance-related examination information on
credit card lending.
Risk Management
Each bank should identify, measure, monitor, and control risk by implementing an effective
risk management system appropriate for the size and complexity of its operations. When
examiners assess the effectiveness of a bank’s risk management system, they consider the
bank’s policies, processes, personnel, and control systems. Refer to the “Bank Supervision
Process” booklet of the Comptroller’s Handbook for an expanded discussion of risk
management.
Management
Credit card lending is a highly automated, high-volume activity that distributes sophisticated
products to consumers. A bank’s credit card operation should have the management and
organizational structure, expertise, staffing levels, information systems, training programs,
and general and specialty audit processes to be effective in this environment. Accountability
and responsibility should be clearly defined at every level.
A bank’s strategy for credit card activities should identify, in broad terms, the level of risk
the bank is willing to accept for various products in its portfolio. The plan should reflect
realistic goals and objectives based on reasonable data and assumptions. The bank’s appetite
for risk often involves balancing its underwriting and the pricing structure to achieve desired
results. For example, a bank may ease its credit standards, and price for that risk through
higher interest rates, projecting increased profits in spite of the higher losses that may be
associated with those accounts. Examiners should assess the adequacy of the bank’s total
strategy.
All banks should implement sound fundamental business principles that identify risk,
establish controls, ensure compliance with applicable laws and regulations, and provide for
monitoring systems for lending activities. Monitoring systems should also provide a
mechanism to identify, investigate, and report suspicious activities. Because credit card
lending includes numerous activities that pose significant risks, the bank should have
effective policies and strong internal controls governing each operational area. Effective
policies and internal controls enable the bank to adhere to its established strategic objectives
and to institutionalize effective risk management practices. Policies also can help ensure that
the bank benefits through efficiencies gained from standard operating procedures.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 14 Credit Card Lending
Risk Management Control Systems
Control systems identify, measure, and monitor risks. These systems include models, loan
review, quality control, audit, and MIS. The structure and function of each system can vary
depending on the size and complexity of the bank’s credit card operations. Technology, level
of sophistication, and staffing levels may also be different. Examiners must determine how
and where each function is performed and assess its effectiveness.
The bank’s audit and loan review functions should conduct periodic reviews of the bank’s
credit card program. Credit card audit programs should be comprehensive, covering the life
of the account and the product overall, including marketing, origination, account
management and servicing, loss mitigation, fraud prevention, and collection. Procedures
should include regular testing of the credit underwriting function for compliance with policy
guidelines and applicable laws, regulations, and regulatory guidance, as well as a review of
all significant policies for prudence and staff adherence to policy. Further, the bank’s audit
function should test controls designed to identify and report suspicious activity.13
A strong credit risk management function is crucial to the ongoing success and profitability
of the credit card program. The risk management function is responsible for evaluating credit
standards, monitoring the quality of the portfolio, and making changes to the underwriting
standards as necessary to maintain the appropriate level of risk in the portfolio. An effective
risk management function promotes early and accurate identification of existing and potential
problems, identifies the need for policy revisions, and provides bank management with the
information it needs to respond promptly to changes.
The risk management process should address the entire cycle of credit card lending, from
strategic development, testing, and product rollout to long-term performance of the portfolio.
OCC Bulletin 2004-20, “Risk Management of New, Expanded, or Modified Bank Products
and Services: Risk Management Process,” provides OCC guidance for national banks.
Examiners should review this issuance when evaluating a national bank management’s
process for introducing new credit card products.14
The risk management function should include responsibility for performing product analyses
to serve as the basis for underwriting, marketing, compliance, and portfolio management
decisions. The function should ensure that marketing initiatives appropriately reflect
acceptable levels of risk. Risk management should help manage and maintain all scoring
systems, analyze portfolio delinquencies and losses, and identify reasons for adverse changes
or trends. It should also monitor portfolio performance, including the performance of specific
products, marketing initiatives, and vintages (refer to the “Glossary” section of this booklet).
 13 Refer to 12 CFR 21.21 and the FFIEC Bank Secrecy Act/Anti-Money Laundering Examination Manual
(December 2, 2014).
14 For FSAs, refer to the Office of Thrift Supervision’s OTS Examination Handbook, section 760, “New
Activities and Services.” 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 15 Credit Card Lending
The bank should have effective MIS in place to perform its risk management functions
effectively. For example, MIS should be able to provide sufficient information to evaluate
and measure the impact of actions taken and identify unusual or suspicious activity. Bank
management should receive reports derived from MIS data outlining portfolio dimensions,
composition, and performance. Reports should include portfolio risk levels, trends,
concentrations, and earnings.15 These reports should be prepared for each product type,
affinity group, or other portfolio segment that may be significant due to strategic importance,
performance related concerns or new products.
Information Technology
Credit card lending is highly dependent on technology. From the time of the loan application
through the remaining life of the loan, information technology (IT) plays a key role in
operations, risk management, and regulatory reporting. IT and the IT infrastructure allow
bankers to leverage resources and increase both operational and financial efficiency.
Additionally, high-volume credit card lenders should have a strong IT culture because of the
high level of MIS and reporting for management and regulatory requirements.
Assessment of IT systems within credit card lenders should include an assessment of the
capability of the IT systems to support the operational, risk management, and risk control
functions of a credit card operation. The assessment also should consider continuity planning
for IT as well as overall resiliency of business processes. IT systems should be compatible
and able to process the high volume of data generated during the life of a credit card.
Scoring Models
Most banks use credit scorecards to some degree in their credit card operations. Credit
scorecards, also referred to as models, are risk-ranking tools that attempt to differentiate
between accounts that will exhibit “good” behavior and those that will not.16 The scores
generated indicate the relative level of risk in either ascending or descending order,
depending on the convention used by the model developer. Credit scoring also is used to
control risk in acquisition and underwriting, account management, and collection processes.
The use of models also can pose risk to the bank—specifically, the risk that the bank will
suffer losses because the bank’s lending strategies are based on poor or failed models. OCC
Bulletins 1997-24, “Credit Scoring Models: Examination Guidance,” and 2011-12, “Sound
Practices for Model Risk Management: Supervisory Guidance on Model Risk Management,”
and appendix H of this booklet, “Credit Scoring and Development of Scoring Models,”
provide additional useful information.
 15 Refer also to the “Loan Portfolio Management” booklet of the Comptroller’s Handbook for further discussion
of MIS reports.
16 The definition of a “bad” account varies but typically involves some level of delinquency, usually more than
60 or 90 days past due.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 16 Credit Card Lending
In simple terms, scoring employs mathematical techniques to predict future behavior based
on past performance. Predictive horizons range from six months to two years. The
assumption is that the behaviors of the scored population going forward will not change
markedly from those of the population used to develop the model. The ability of models to
differentiate risk deteriorates with time, however, as a result of shifts in consumer behavior,
economic conditions, and bank and industry product terms and marketing.
The majority of scoring models rely on statistical regression techniques (linear, logistic, or
neural network), but banks occasionally use nonempirical “expert” models. Expert models
are designed using subjective and judgmental factors such as age; therefore, usage is limited
because Regulation B (which implements the ECOA) contains specific requirements for use
of an applicant’s age in scoring models.17 Risk models are programmed to generate adverse
action reason codes.
Models are categorized as either generic or custom. Generic, off-the-shelf scorecards are also
known as pooled data models because the developer uses information obtained from multiple
lenders or credit repositories or bureaus to create the model. Generic scorecards are most
often used when the bank lacks a sufficient number of approved and denied applications or
depth of account history to provide the requisite development sample to build a custom
scorecard (i.e., the bank does not have enough data to generate statistically valid
conclusions). Some pooled data models are developed specifically for credit cards.
Proprietary or custom scorecards are bank- or product-specific models developed using the
bank’s own data and customer experience. These scorecards may be developed in-house, if
the bank has the modeling expertise on staff, or scorecards may be developed by modeling
vendors.
Scoring systems do not normally consist of a single model. Recognizing that there are
differences in available information and behavior patterns, the modeler attempts to segment
the group into similarly situated subpopulations. The modeler can then develop individual
scorecards for each distinct subpopulation that use the variables most predictive of risk for
that particular group, thereby increasing accuracy and precision. For example, a credit card
application might consist of seven models: a “thin file” scorecard for applicants with little or
no previous credit history; three “derog” or “subprime” models for those with prior
delinquencies; and three “prime” scorecards for those with more substantial credit histories
who have been paying on time. The definition of the subpopulations and the determination of
how many to use are key components of the model development process.
Banks’ use of risk models in the underwriting process varies. Banks may
• use scoring models exclusively to approve or reject loan applications.
• rely heavily on scoring, using automated underwriting systems to approve high scores
and reject low scores, but divert borderline scores to underwriters for further review (also
called “gray zone” strategies).
 17 Refer to 12 CFR 1002.6. Banks should ensure that credit scoring models comply with all applicable fair
lending laws, regulations, and guidance, including other provisions of Regulation B, such as 12 CFR 1002.4.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 17 Credit Card Lending
• use scores as one among many inputs in a judgmental underwriting process.
• use scores to route applications between senior and junior underwriters or for some other
queuing strategy.
Most large retail credit operations fall into the second category above, while smaller banks
with low volume tend to fall into the third category. The types of scores generated by risk
models include the following:
• Credit bureau risk scores: The most widely used of all the scores, bureau scores use
only information on file at the three major credit bureaus; loan-specific information and
general economic conditions are not included in these models. For the most part, bureau
scorecards (e.g., FICO, formerly known as Fair Isaac Corporation, and VantageScore)
have been developed by vendors, although a few large banks have collected enough data
over time to develop their own internal bureau scores. For example, FICO developed and
maintains several bureau scorecards (e.g., Classic FICO, FICO8, FICO NextGen) that are
used to underwrite and manage mortgage, credit card, and auto loan portfolios. Although
the models that each bureau uses are somewhat different, they all consist of the same
number of sub-scorecards and assign a three-digit number ranging from 300 to 850,
which quantifies the relative ranking of consumers according to general credit quality.
The higher the customer score, the lower the credit risk. Each bureau has a name for its
own scoring system: “BEACON” at Equifax, “EMPIRICA” at TransUnion, and “FICO”
at Experian. In March 2006, the three bureaus launched a new scoring model called
VantageScore to compete with FICO in selling scorecards to banks. VantageScore also
rank orders consumers using scores from 300 to 850.
Credit bureau scores consider five general groups of predictive variables:
– Previous performance, including the severity and frequency of poor performance and
how recently the poor performance occurred.
– Current level and use of nonmortgage debt.
– Amount of time that credit has been in use.
– Pursuit of new credit and inquiries.
18
– Types of credit available.
• Application scores: As the name suggests, application scores incorporate information
from the loan application as well as various credit bureau data, possibly including the
bureau score. In some cases, the model may also consider information related to the
transaction being financed. The score may be used to determine pricing, as well to decide
approval or denial.
Once the accounts are booked, the bank uses additional models to help manage the portfolio.
Banks can use scores for monitoring portfolio risk, implementing account management
initiatives, targeting cross-selling opportunities, and prioritizing collection activities. These
scores may include the following:
 18 Multiple inquiries in a short period of time are usually eliminated, or “de-duped,” so that the consumer is not
penalized for rate shopping. In addition, non-consumer-originated promotional inquiries are excluded.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 18 Credit Card Lending
• Behavioral scores: These models generate scores based on customer performance on the
bank’s loans (e.g., payment and delinquency patterns). Whereas traditional behavior
scorecards were confined to internal, or “on us,” borrower performance, many models
now include bureau scores or certain bureau report characteristics in the scores.
Transactional behavior models, such as those used for fraud identification, can rescore
credit card accounts after individual transactions. Some collection departments use
specialized behavior models based on the performance of delinquent borrowers.
• Bankruptcy scores: These are designed to identify customers posing a higher risk of
bankruptcy based on the attributes of borrowers who have declared bankruptcy.
Bankruptcy scores usually are used in conjunction with conventional credit risk models.
Banks may also use non-credit-risk models in the account acquisition, underwriting, and
account management processes. These models include the following:
• Marketing: Target marketing initiatives to meet preferences or perceived needs.
• Response: Target prospects most likely to respond to an offer.
• Revenue: Project the level of revenue a customer will generate for the life of the loan.
• Attrition: Identify accounts likely to prepay or voluntarily close.
• Fraud: Identify potentially fraudulent applications or credit card transactions.
Bankers sometimes combine multiple scorecards. This practice is also known as model
layering or matrixing, through which the bank benefits from combining the risk selection
capabilities of the various models used. Matrixing lets the bank adjust the cutoff on a cell-bycell,
stair-step basis, allowing for “swap sets.” This enables the bank to approve the best of
the customers, who may or may not have been approved based on a fixed cutoff score.
Effective use of matrixing encourages a bank to develop a “joint delinquency table” (which
can be converted to a “joint odds” table) from the combination of multiple scorecards.
The “swap set” concept is illustrated in table 1, in which the application scores are on the
vertical axis and the bureau scores are on the horizontal axis, with the risk decreasing as
scores increase. The percentages in the body of the table represent the frequency with which
an account was ever delinquent within a defined time period.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 19 Credit Card Lending
Table 1: Joint Delinquency Matrix, Delinquency Rates
Less than
600 600–649 650–699 700–749
750 or
higher
Average
delinquency
rate by custom
score segment
Less than 180 20% 14% 14% 11% 8% 13.4%
180–199 13% 11% 10% 6% 7% 9.4%
200–219 11% 10% 7% 5% 5% 7.6%
220–239 10% 7% 5% 4% 5% 6.2%
240 or higher 8% 3% 3% 2% 1% 3.4%
Average
delinquency rate
by bureau score
segment
12.4% 9.0% 7.8% 5.6% 5.2%
Assume, for simplicity, that the delinquency chart is based on the performance of 2,500
borrowers evenly distributed over the 25 cells (i.e., 100 borrowers in each cell).
If the bank’s tolerance for risk is associated with a delinquency rate of roughly 6 percent, a
cutoff score of 200 using only the custom scorecard would achieve that objective (the
delinquency rate based on a custom score greater than 200 would be 5.7 percent) based on a
portfolio of 1,500 borrowers. The bank could lower the average delinquency rate to
5.1 percentan 11.6 percent reduction in the delinquency ratewithout decreasing volume
by overlaying the bureau score and swapping out poor performers (i.e., bureau scores below
650) with custom scores greater than 200 and swapping in better performers (i.e., bureau
scores greater than 700) with custom scores less than 200.
Banks also layer credit scores with nonrisk scores (e.g., risk, revenue, and response models
may be used together for a pre-approved credit card solicitation). This practice presents
difficulty in that the purposes of the models used may conflict. Although management tries to
control credit risk by using the risk score, revenue and response scores generally increase for
higher-risk borrowers (reflecting higher potential for revenue generation in terms of pricing
and fees and greater propensity to respond to credit offers). This may result in adverse
selection (e.g., higher-risk borrowers are more likely to respond). The odds associated with
the risk score can be adversely affected as fewer “good risk” prospects respond relative to the
level of “bad risk” prospects. Management’s planning should reflect a solid understanding of
the risks associated with the use of these types of strategies.
Model Documentation
Bank policy should address requirements for maintaining model documentation. Acceptable
forms of documentation may include the following:
• Model inventory: Summary listing of all models in use, their application(s), and the
dates developed, implemented, and last validated.
• Individual models: Model documentation that is understandable and sufficiently detailed
to allow for precise replication should the need arise.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 20 Credit Card Lending
• Chronology log: Listing by date of all significant internal and external events relevant to
the credit function (score implementation, product changes, cutoff score changes, major
marketing initiatives, economic or competitive shifts, etc.).
Models purchased from vendors should come with comprehensive manuals describing
development, as well as ongoing maintenance and validation requirements.
Model Management and Tracking
Banks using scoring systems should have the management expertise and processes in place to
evaluate the models, ensure their appropriate use, monitor and assess their performance on an
ongoing basis, and ensure proper validation. This oversight also should extend to any
scoring-based strategies employed. OCC Bulletins 1997-24, “Credit Scoring Models:
Examination Guidance,” and 2011-12, “Sound Practices for Model Risk Management:
Supervisory Guidance on Model Risk Management,” provide guidance for scorecard
management.
Any time a credit decision is made that is contrary to that indicated by the customer score, it
is known as a scoring override. Requests that meet or exceed the score cutoff but that are
denied are known as high-side overrides.
19 Requests that fail the cutoff but are approved are
known as low-side overrides. Not only are these policy exceptions, but excessive levels of
overrides may diminish the effectiveness of the scoring models and may be indicative of
illegal discrimination on a prohibited basis (causing a violation of Regulation B).20
Furthermore, approved loans that fail to meet the score cutoff often perform worse than loans
above the cutoff. Bank management should evaluate low-side overrides by comparing them
with the bad rate at the lowest score band above the cutoff; the highest-scoring overrides just
under the cutoff should theoretically outperform the marginal passes in the next-highest score
band.
Override tracking is an important control. Bank management should track override
performance by reason, channel, analyst approving credit, and score band, and monitor the
volume, the reason codes, and the quality of the override segment. It is important to know
why some applicants with low scores are approved and others with high scores are denied.
Override volume and quality may support the need for underwriting criteria or score cutoff
changes. Table 2 shows an example of override tracking.
 19 A high-side override can occur when the bank considers variables or characteristics that were excluded from
the model.
20 Under Regulation B, the prohibited bases are race, color, religion, national origin, sex, marital status, age, the
fact that all or a part of the applicant’s income derives from any public assistance program, or the fact that the
applicant has in good faith exercised any right under the Consumer Credit Protection Act or any state law on
which an exemption has been granted by the CFPB. Refer to 12 CFR 1002.2(z).
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 21 Credit Card Lending
Table 2: Example of Override Tracking
Scorecard Overrides
Score range
Number of
overrides
approved
Percentage
of overrides
approved
Number of
overrides
denied
Percentage
of overrides
denied
Percentage
of bad loans
(volume)
Percentage
of bad loans
(dollars)
800 or higher 50 100% 0 0% 1% 1%
750–799 100 95% 5 5% 1% 2%
700–749 200 93% 15 7% 2% 4%
675–699 300 88% 40 12% 3% 6%
650–674 400 89% 50 11% 5% 9%
625–649 60 15% 350 85% 8% 15%
600–624 10 9% 100 91% 11% 20%
Less than 600 2 4% 50 96% 100% 100%
Bank management should track low-side overrides by number as well as by dollar balances.
Generally, banks establish low-side and high-side override limits.
Scorecard-tracking MIS are crucial for effective scorecard management and provide valuable
information for risk management and marketing. Bank management generally monitors
model performance to determine how much the bank’s customer population has changed, to
analyze and adjust cutoffs, and to determine when it is time to redevelop a model. Reporting
frequency varies from monthly to quarterly, depending on volume and the level of risk
involved.
Scorecard MIS comprise two broad categories: front-end population stability reports and
back-end performance reports. Front-end or stability reports measure score distribution
changes in the customer and essentially determine whether the customer population is
changing. This is important because if the population changes significantly, it triggers the
need for additional model analysis and, possibly, model adjustment (e.g., recalibration,
alignment, or weighting) or redevelopment.
Key front-end modeling reports include the following:
• Application distribution reports: Track approvals and denials and high- and low-side
overrides by score band, provide feedback on application volumes and the success of
marketing programs, and serve as an early warning of shifts in the risk profile.
• Population stability reports: Identify changes in the population by comparing score
distributions of the developmental sample with current production.
• Characteristic analysis reports: Triggered when population stability changes, these
reports compare the base population with actual results for individual attributes. Bank
management should track every attribute individually. Vendors often provide
developmental sample population factors in scorecard manuals. If not, banks can form a
benchmark population from the first use of sample population and track population
stability over time.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 22 Credit Card Lending
• Scoring accuracy reports: Present the volume of scoring errors sorted by those deemed
significant versus minor. Significant errors may represent miscalculated scores resulting
in decisions on overrides that are inconsistent with the cutoff; minor errors are mistakes
that if corrected would not alter the credit decision.
Back-end quality reports compare actual versus expected results, and essentially determine
whether scorecards still differentiate risk sufficiently. Bank-end reports serve the dual
purpose of measuring model efficacy and evaluating overall portfolio quality.
Key back-end reports include the following:
• Vintage tables and charts: Measure the performance and trends of accounts originated
each month or quarter. These generally are the most fundamental and indispensable
model and portfolio management tools.
• Delinquency distributions reports (DDR): Compare scores with subsequent
performance and show whether scorecards continue to accurately rank-order risk. DDRs
present coincident delinquencies and actual delinquencies at a point in time.
• Maximum delinquency distributions reports (MDDR): Identical to DDRs, except that
MDDRs show “ever delinquent” statistics, which include delinquent loans that were
cured, repaid, or charged off. Delinquencies are presented using the same “bad rate”
definition used in the model development.
• Benchmarking: The post-implementation vintage tables or charts and delinquency
distributions should be benchmarked against the performance distributions generated
from the development sample to determine whether the models are performing as
expected. The distributions and tables based on the development data should reflect the
bank’s best guess of expected outcomes. Moreover, trends in the benchmarking analysis
would be evaluated to differentiate between random, but temporary, deviations in
performance (which may require minor changes in strategies) from permanent,
systematic deviations (which may require recalibration or redevelopment of the models).
• Chronology logs: Identify internal and external changes that are expected to affect model
performance and the credit function so that a model can be properly evaluated in the
future. For example, a chronology log records important external macroeconomic
indicators, such as recession or changes in the unemployment rate, and internal changes
such as changes in cutoffs, collection strategies, or override policies.
• Early-warning analysis: Uses benchmark performance over shorter time horizons than
those used in the development of the model. Although the performance window from
many scoring models is 24 to 36 months, waiting up to three years to generate a valid
back-end analysis may be an unsafe or unsound practice. For that reason, early-warning
performance benchmarks based on the performance of the model development sample
over shorter performance horizons (e.g., 12, 15, and 18 months) should be constructed
and used to project the performance of the current portfolio over the next 24 to 36
months.
Scorecard tracking reports should be comprehensive and consistent with the purpose of the
model and should use a level of rigor reflecting the importance of the model in the decision 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 23 Credit Card Lending
process. Statistically valid tests should be used in lieu of judgment-based evaluation of
charts.
Vendors and credit repositories periodically publish scorecard odds for generic models.
Although the data can be informative and useful when implementing a new model, the data
are often outdated and differ significantly from individual bank results. Such pooled-data
odds are generally not an appropriate substitute for basic scorecard tracking by banks that
depend on the models. Banks should perform formal revalidations using a discrete sample of
applications and should regularly compute model separation measurements (e.g.,
Kolmogorov-Smirnov, or K-S, scores, chi-squared test).
It is important for bank management to understand (1) which models are deployed; (2) how
the models are used; (3) what control systems are in place to manage and monitor model
performance; (4) how cutoffs and strategies are developed; (5) how risk/reward tradeoffs are
made; and (6) how bank management analyzes portfolio and vintage performance and uses
that information to alter or improve targeting, underwriting criteria, cutoffs, and other scoring
strategies. In short, bank management should determine whether the bank’s models and
related risk management processes ensure that risk remains within approved tolerances.
Marketing and Underwriting of New Accounts
The competition in the credit card industry, combined with the relative saturation of the
market, makes new account acquisition a key component of a successful credit card program.
Marketing for new accounts has evolved from a relatively simple process of offering credit
cards to existing bank customers through “take-one” applications in branches to active
marketing and solicitation via diverse media channels across a large, often nationwide,
market. More specifically, account acquisition is most often accomplished through three
distinct methods: prescreened solicitations (typically using direct mail); approval of
completed applications; and portfolio acquisitions from third parties. Each method should
include sound underwriting practices to achieve and maintain desired portfolio quality.
Marketing is expensive and carries risk. Even successful marketing programs can leave the
bank with a new population of customers with higher risk profiles than the bank initially
sought. A bank’s marketing program typically depends on its size, strategy, and growth
plans, appetite for risk, and distribution network. The bank’s risk management function
should be responsible for ensuring that marketing initiatives reflect the levels of risk
acceptable to management. The bank’s marketing activities should be guided by a detailed,
realistic marketing plan that is consistent with the overall goals and objectives of its strategic
plan and in compliance with applicable laws and regulations.21 Policies and procedures
should ensure that functional areas of the bank (e.g., credit risk management, operations,
systems, legal, and compliance) are appropriately involved in all aspects of the marketing
 21 For example, marketing materials are subject to the advertising and solicitation requirements in Regulation Z.
Refer to 12 CFR 1026.16 and 1026.60. Also, banks should ensure that marketing programs comply with the
ECOA and all other applicable fair lending laws; section 5 of the FTC Act, which prohibits unfair and deceptive
acts or practices; and section 1036 of the Consumer Financial Protection Act (CFPA), which prohibits unfair,
deceptive, and abusive acts or practices.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 24 Credit Card Lending
process. Other important components of a successful marketing program include experienced
and competent management and staff, reliable projections and market analyses, and complete
and accurate MIS reports that track performance by product and initiative (such as a specific
promotional or balance transfer program).
Prescreened Solicitations
In a prescreened solicitation program, a credit card issuer generally uses a list of potential
customers to whom it will make firm offers of credit. Compilation of the list of names is
typically a joint effort involving the bank’s marketing and risk management functions or
credit divisions. Marketing is usually responsible for identifying the targeted population,
creating the products the bank offers, and controlling marketing costs. The risk management
function’s main responsibilities generally include establishing the prescreening credit criteria,
establishing credit lines, ensuring compliance with appropriate consumer and fair lending
laws and regulations, and monitoring the success of the program after the accounts are
booked. The area in the bank responsible for the finances of the credit card program may
play a key role in projecting the impact that credit and marketing decisions will have on the
profitability of new accounts obtained through prescreened solicitations.
Before proceeding with any prescreened solicitation program, the bank should ensure that it
has the systems necessary to capture and monitor needed data once accounts are booked. For
example, systems may need to capture credit bureau scores, number of respondents, and
reasons an applicant’s credit score may decline after approval.
Credit card issuers usually plan prescreened campaigns throughout the year to obtain new
accounts. They may either purchase a list of names from a list vendor or from the credit
bureaus, or they may identify a segment of the bank’s customers. The bank then provides
these lists of names, along with written instructions of its prescreened criteria, to the credit
bureaus to start the prescreening process. Banks generally specify two types of criteria:
exclusion and credit.
Exclusion criteria are applied to eliminate prospects that the bank does not want to consider
in the mailing. These prospects are not scored. People with seriously derogatory credit
histories are examples of excluded prospects.
Credit criteria are then used to subdivide the remaining prospects into different groups.
Issuers commonly incorporate credit bureau scores into these levels of credit criteria to create
marketing initiatives targeting prospects whose score ranges suggest a higher probability of
good performance rates. The different criteria levels allow the bank to market to individuals
with the overall risk profile it desires and to offer variations in the product and pricing based
on risk. Prospects usually are segmented into categories such as A, B, C, D, etc., with the
A category comprising the lowest-risk consumers. Prospects that do not qualify for level A
are considered for level B, those that do not qualify for level B are considered for level C,
etc. The last level includes consumers who do not qualify for the higher levels but passed the
general exclusion criteria.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 25 Credit Card Lending
Banks also establish criteria for credit line assignments. Some banks assign the credit line up
front and disclose it to the consumer as part of the prescreened offer.
Another common approach is for banks to offer the consumer a credit limit up to a certain
amount. The bank does not assign the credit line until after the consumer responds to the
solicitation. The criteria that each bank uses vary, but may be based on a combination of
disclosed income, credit bureau score, and criteria level.
Certain practices in connection with this type of “up to” marketing present high compliance
and reputation risks. As a result, banks should not engage in practices that could be
considered unfair, deceptive, or abusive, including the following:
• Targeting consumers who have limited or poor credit histories with solicitations for a
credit card with a maximum, or “up to,” credit limit that is far greater than most of these
applicants are likely to receive.
• Providing most applicants with a “default credit line” (the lowest credit line available)
that is significantly lower than the maximum amount advertised, while failing to disclose
fully and prominently in the promotional materials the default credit line and the
possibility that the consumer will receive it.
• Advertising possible uses of the card when the initial available credit line may be so
limited that the advertised possible uses are essentially illusory.
Banks should also consider providing and disclosing a readily exercisable mechanism for
consumers to cancel the card at little or no cost when they learn the actual credit limit
granted.22
Prescreened solicitation campaigns often include a promotional rate to attract customers and
to induce new and existing customers to transfer balances from other credit cards. A typical
promotional rate solicitation involves representations that an applicant or current cardholder
may, for a limited time, receive a reduced APR on certain credit card charges or transactions.
The reduced APR generally is in effect for only a specified period of time.23
Once the credit bureau prescreens the list of prospects against the bank’s criteria, the bank
has the opportunity to review the breakdown by criteria level. The information the bank
receives at this point does not have identifying information about the consumers, such as
names and addresses. This is done to avoid triggering provisions of the FCRA. Therefore, the
bank can still eliminate prospects if it wants to reduce the size of its overall mailing or the
number of consumers solicited within a certain criteria level.
The Consumer Compliance series of Comptroller’s Handbook booklets; the OTS
Examination Handbook, section 1300, “Fair Credit Reporting Act,” and related “Program”;
 22 Card issuers cannot impose a fee on consumers who close their accounts. Refer to
12 CFR 1026.52(b)(2)(i)(B)(3).
23 Such promotional offers are subject to limitations and disclosure requirements in Regulation Z. Refer to
12 CFR 1026.16 and 1026.60.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 26 Credit Card Lending
and other related issuances describe FCRA and relevant provisions of the Fair and Accurate
Credit Transactions Act of 2003 (FACT Act). These resources also provide information on a
bank’s ability to deny credit to consumers targeted in a preapproved solicitation campaign.
With few exceptions, once the bank receives the list with prospect names and other
identifying information, the bank should make a firm offer of credit to each consumer on the
list. As a result, the bank should ensure that the list is based on the criteria that it submitted to
the credit bureaus and list processors. For example, the bank should complete audits to
ensure that the credit bureaus applied the correct credit criteria (i.e., the criteria the bank
originally submitted, which may differ from its current criteria). The bank should complete
this audit after the credit bureau prescreening, but before taking delivery of the names.
Many banks use a third-party list processor throughout the prescreening process. The list
processor performs various steps, such as eliminating duplicate names and existing
cardholders and verifying addresses. The bank may also use scoring models to help identify
consumers who would be more likely to respond and to provide more income to the bank by
revolving their balances. Identifying more likely responders has become a very important
aspect of prescreening campaigns, since industry reports show that response rates have
declined from around 5 percent to less than 1 percent in recent years.
After the bank receives the prospect names, it solicits the consumers by direct mail,
telemarketing, social media, or a combination of these and other solicitation efforts. The bank
or a third party then processes the consumer responses. Some banks then obtain updated
credit bureau information on all responders. This may lead to a favorable or unfavorable
change in credit score, not necessarily because a consumer’s behavior has recently changed,
but because the bank now has a more complete profile of the borrower. Once the bank books
the new accounts, its risk management function should analyze the results and characteristics
of the responders to determine whether the bank was successful in attracting the types of
consumers it intended to target.
Results of previous prescreened solicitations provide valuable information for future
programs. One method the risk management function may use to analyze results is to
complete a vintage analysis. Bank management may organize vintages by solicitation
campaign or by quarterly or annual periods. At a minimum, most vintage reports include
delinquency and credit loss information. A more comprehensive vintage report would include
bankruptcy, activation, utilization, and attrition information. Vintage reports are an effective
way to compare the performance of various segments of the portfolio, based on the
origination period and acquisition method. The reports also can be used to compare actual
with projected performance to enable the risk management function to determine the reason
for significant differences.
A bank’s risk management function typically helps establish credit criteria and performance
projections before the prescreened solicitation campaign is executed. Risk management also
should promptly and thoroughly analyze the results of major prescreened solicitation
programs. The risk management function should first review the results of prescreened
solicitation campaigns within a relatively short time, such as three months, to determine the
quality and quantity of responders. Shortly thereafter, risk management should review 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 27 Credit Card Lending
activation rates, balances, and delinquencies. For the next six months to a year, risk
management should review the financial results of each major prescreened solicitation
campaign and compare these results to the initial forecasts.
An effective account acquisition program usually includes testing changes in credit standards
and marketing practices before full rollout of the campaign. A bank’s testing program should
have defined objectives and requirements for analysis, review, and decision making. A bank
may perform a wide variety of tests to evaluate variables, such as changes in criteria, cutoff
scores, and pricing and product type.
For example, assume a bank plans to solicit 1,000 names for a prescreened offering. One test
may allow 50 of those solicited to have two 60-day delinquencies on credit reports within the
previous 12 months, even though this population normally would be excluded from offers.
These 50 are the test group. The remaining 950 solicited consumers are the control group.
Bank management then monitors the test group’s performance in relation to the control group
until management can reach a reasonable conclusion about the effect of the change in
delinquency standards. The time period for tests may vary, depending on the credit standard
or borrower characteristic management is testing. It may take up to 18 months before a bank
can make a valid conclusion regarding changes to credit criteria.
Applications
Banks market credit card applications in various ways, including via the Internet, direct mail,
telemarketing, magazine inserts, and countertop “take-one” applications. Most banks use an
automated application processing system to process applications. Typically, information
from applications filed electronically goes directly to an issuer’s application system, while an
analyst may manually process an application mailed to the bank. The bank automatically
obtains a credit bureau report in connection with processing an application. The bank should
have a system in place to ensure that data from the applications are entered correctly.
In recent years, major issuers relied primarily on automated scoring systems to decision
credit card applications, with a small segment of applications referred to judgmental
underwriting. Judgmental underwriting involves undertaking a manual review using the
bank’s underwriting policy and established guidelines that define the quality of new
accounts. When credit scoring is used to grant credit, quality is controlled by setting the
cutoff score based on the desired loss rate. Because of the volume of applications and the
desire for rapid decision making, most large issuers use scoring. When judgmental
underwriting is included in making the credit decision, it should be tightly controlled to
ensure that underwriters or analysts consistently follow policy and comply with applicable
consumer protection and fair lending laws and regulations. The bank controls the quality of
new accounts by establishing well-understood controls and credit guidelines in its policy and
performing routine quality control reviews.
The CARD Act introduced an additional legal requirement to the underwriting process: A
card issuer must consider a consumer’s ability to make the required minimum periodic 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 28 Credit Card Lending
payments under the terms of an account.
24 Specifically, issuers must determine an applicant’s
ability to pay based on an assessment of the applicant’s current or reasonably expected
income or assets and his or her current debt obligations. The card issuer may limit its
consideration of a consumer’s current or reasonably expected income or assets to the
consumer’s independently verifiable income or assets. To meet the ability-to-pay
requirement, issuers should have access to information regarding the applicant’s income or
assets and current obligations at the time of application. This information may be available in
several ways: The applicant may provide it at application; the issuer may have access to
recent information (e.g., within 12 months) through other established bank products, as well
as from third parties (such as data aggregators) or affiliates, subject to applicable
information-sharing rules; or the information may be estimated through an income estimator
model that is “empirically derived, demonstrably and statistically sound.”25
The underwriting process varies among issuers. The proportion of scored versus
judgmentally decided applications is not always the same. Most issuers choose to assess
ability to pay as the last step in the approval process, but issuers do not have to wait until the
end of the process to do so. Whatever the bank’s underwriting structure, however, bank
management should have established and implemented well-defined guidelines for the credit
approval process to mitigate consumer compliance, BSA, and credit risk.
Portfolio Acquisitions
Investors acquire credit card portfolios for many reasons. They may want to expand an
already established credit card business quickly, realize improved economies of scale,
diversify product lines or niches and geographic markets, or increase profits. A seller, on the
other hand, may wish to reinvest in other investments, recapitalize its business, or increase
liquidity. Whatever the reason, there are markets for credit card portfolios, and the premiums
can be lucrative.
Banks should have procedures, systems, and controls in place to govern portfolio
acquisitions. Procedures provide consistent analysis throughout the acquisition process and
reduce the risk that a critical item or aspect of the transaction will be overlooked. The
procedures should incorporate detailed instructions regarding such areas as prospective
portfolio reviews, due diligence, and final analysis.
Further, the due diligence review should include an assessment of the selling institution’s
customer identification program (CIP) and BSA, anti-money laundering (AML), and Office
of Foreign Assets Control (OFAC) procedures to determine whether the selling institution’s
activities are consistent with the acquiring bank’s procedures. Also, credits that are
inconsistent with the acquiring bank’s risk management should be identified and removed
from the portfolio acquisition. If the portfolio contains subprime credit cards, the bank should
refer to the guidance in OCC Bulletin 1999-10, “Subprime Lending Activities: Interagency
Guidance,” and OCC Bulletin 1999-15, “Subprime Lending: Risks and Rewards.” Although
 24 Refer to 12 CFR 1026.51.
25 Refer to 12 CFR 1026, supplement I, comment 51(a)(1)(i)-5.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 29 Credit Card Lending
OCC Bulletin 1999-15 does not apply to FSAs, it describes prudent practices that FSAs may
wish to consider when managing a portfolio containing subprime credit cards.
Examiners should test a sample of new accounts to determine the level of adherence to the
bank’s policies and the quality of accounts coming into the bank. Sampling techniques are
discussed in detail in appendix A, “Transaction Testing.” (Refer to the “Purchased Credit
Card Relationships” section of this booklet and appendix J for a discussion of intangible
assets resulting from credit card portfolio acquisitions.)
Account Management
Account management is the loan administration piece of credit card lending and describes the
treatment of booked accounts. As with account acquisitions, account management should
include heavy involvement from risk management or risk policy, marketing, operations,
compliance, customer service, customer retention, and payment processing.
The guidance issued in OCC Bulletin 2003-1, “Credit Card Lending: Account Management
and Loss Allowance Guidance,” covers such areas as credit line management, over-limit
practices, minimum payment and negative amortization, workout and forbearance practices,
income recognition and loss allowance practices, and policy exceptions. Although the
“Introduction” section of this booklet discusses account management in general terms,
examiners should refer to OCC Bulletin 2003-1 during the examination process. Examiners
should also review the steps in the “Examination Procedures” section of this booklet, as well
as the steps in appendix A, “Transaction Testing.”
The account management process begins with monitoring at the levels of portfolio, portfolio
segment (e.g., product, vintage, credit risk, marketing channel), and account. Bank
management relies on MIS and tools, such as behavioral and credit bureau scoring, to
identify positive and negative trends. Analyses of those trends and the reasons behind them
provide bank management with a basis for strategies to enhance performance and maximize
profitability. These strategies often involve credit decisions. The analysis should also cover
the types of activities in which customers engage and should include a determination whether
the activities are consistent with similarly situated customers. Bank management should
develop the eligibility requirements and treatment characteristics as carefully as it does the
underwriting criteria for the product.
Account management strategies can be used on an individual account basis, or for entire
portfolios or selected segments of portfolios. The strategies can be manual or automated.
Regardless of the strategies employed, banks should develop and implement policies and
procedures that adequately monitor and control the assumed risk and that provide for
consistent treatment of similar customers. In community and midsize banks, account
management processes are typically not as formal and automated as they are in larger banks.
Examiners should assess whether account management processes are commensurate with the
size of the retail function and complexity of the products.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 30 Credit Card Lending
Some banks use a one-size-fits-all approach to account management, in which there is one
option and the customer either meets the criteria or does not. Other banks deliver a range of
options based on each customer’s creditworthiness and needs. The latter approach requires
extensive use of technology and system support, but can expand the account management
options that the bank uses and prove to be more profitable in the long run.
Just as with initial product design, bank management should test account management
initiatives before full implementation, as described in OCC Bulletins 2003-1, “Credit Card
Lending: Account Management and Loss Allowance Guidance,” and 2004-20, “Risk
Management of New, Expanded, or Modified Bank Products and Services: Risk
Management Process.”26 Banks often use a “champion/challenger” technique to test account
management initiatives, in which the existing practice is deemed the champion and one or
more modifications applied to smaller portions of the portfolio are tested and deemed the
challengers. After observing performance over a period, usually several months, the account
treatment that was changed in or applied to a well-performing challenger may be applied to a
larger population or may even replace the champion. Conversely, poorly performing
strategies are either modified or discontinued. Ongoing and thorough analyses are critical to
reaping the benefits of multiple strategy scenarios. For the strategies to be meaningful, it is
important that the strategy populations be isolated from other account management strategies.
Otherwise, it may be impossible to determine factors contributing to the outcome with any
degree of reliability.
Some of the more common account management activities are described in the following
sections.
Line Increases and Decreases
Generally, lines are increased for account holders who have demonstrated the financial
capacity to perform on a new, higher credit limit. It is important to note that line increases
must be supported with information documenting a cardholder’s ability to pay. Refer to
12 CFR 1026.51 and the “Truth in Lending Act” booklet of the Comptroller’s Handbook for
information on ability-to-pay requirements and guidance. Conversely, lines may be decreased
for account holders showing negative financial trends, based either on performance on the
bank’s credit card account or credit bureau information. Current account line decrease
programs generally do not reduce line amounts below outstanding balances. In addition,
Regulation Z requires the issuer to provide advance notice of the decrease before an over-thelimit
fee or a penalty rate can be imposed solely due to the consumer exceeding a newly
decreased credit limit. Refer to 12 CFR 1026.9(c)(2)(vi).
Applying line decreases to current accounts is a difficult issue. Credit line assignments have
been a major competition point for many years, and customers may view them as a status
symbol or indication of value to the bank. As banks strive to better control unfunded
commitment exposure, however, they may reduce credit card limits to better reflect an
account holder’s typical line usage and financial resources.
 26 Refer to footnote 12.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 31 Credit Card Lending
A bank may also suspend or freeze a line at the cardholder’s current balance. This account
management activity is typically applied when a borrower experiences financial difficulties
and is used in conjunction with a temporary or long-term workout program. These programs
are discussed in the “Collections” section of this booklet.
Over-Limit Authorizations
Banks generally maintain guidelines to determine whether accounts are authorized for
transactions that exceed customer credit lines and to determine how much excess is allowed.
For example, credit card accounts of the most creditworthy individuals may be approved to
allow those customers to exceed their credit limits by 20 percent to 30 percent.
Over-limit approvals should be granted for only a bank’s most creditworthy account
holders.
27 Assigned credit limits should accurately reflect the dollars a bank is willing to risk
with a given customer (based on his or her financial capacity and condition). Over-limit
approvals are underwriting exceptions and should be identified, tracked, and reported as
such. Further, over-limit practices should be carefully managed and focus on reasonable
control and timely repayment of amounts that exceed established credit limits. Alternatively,
the credit card account holder agreement may require that over-limits be cured when billed;
in this case, if the cardholder remits only the minimum payment required (usually calculated
as 1 percent of the principal, along with finance charges, and fees), then the account is
considered delinquent. Banks should ensure that consumers have clear and full notice of the
consequences of an over-limit.28 In addition, an issuer should not assess a fee or charge for
an over-limit transaction unless the consumer affirmatively consents (or opts in) to the card
issuer’s payment of over-limit transactions. Regulation Z contains additional requirements
for over-limit authorizations and fees.29
If accounts routinely exceed credit limits, then the bank’s board or management should be
concerned either with the initial line assignment or with the risk management process. In
addition to chronic over-limit accounts, over-limit approvals for accounts that previously
exhibited high and generally unused line assignments could signal credit problems.
Management should assess the bank’s over-limit policies and their impact on an ongoing
basis.
 27 Bank management should maintain policies that ensure consistent treatment of similarly situated customers in
these over-limit authorization decisions (and other account decisions discussed in this booklet, e.g., approvals
and line increases) to avoid infringing fair lending laws and regulations. These include section 5 of the FTC
Act, which prohibits unfair or deceptive acts or practices, and section 1036 of the CFPA, which prohibits unfair,
deceptive, or abusive acts or practices.
28 The notice in the original credit card agreement might not be sufficient to prevent a card issuer’s treatment of
over-limits from being considered an unfair, deceptive, or abusive practice in some cases.
29 Refer to 12 CFR 1026.56 for these requirements.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 32 Credit Card Lending
Repricing of Accounts and Other Changes to Credit Terms
Credit card issuers may increase a cardholder’s APR to address credit risks that arise when
the cardholder fails to make timely payments on the account; this is referred to as penalty
pricing. If the cardholder makes timely payments for six consecutive months at the higher
rate, however, Regulation Z requires that the APR be returned to the rate charged before the
increase. Refer to 12 CFR 1026.54 and the “Truth in Lending Act” booklet of the
Comptroller’s Handbook for disclosure and other requirements related to penalty pricing.
Account Closures
Banks should have a policy governing when an account should be closed. Policies and
procedures should also require reporting of suspicious activities, including suspected identity
theft, when appropriate. Although account closure typically occurs as a result of collection
and loss mitigation activity, bank management should also consider circumstances under
which current accounts should be closed to control risk, contingent liabilities, and cost.
Examples of appropriate line closures include accounts of deceased customers, accounts of
bankrupt customers, accounts that have been inactive for a specified time, and accounts that
show significant financial deterioration over a relatively short time. Policies and procedures
should recognize that there are fee and interest restrictions for accounts, for example, in cases
of bankruptcy or a deceased customer. Further, the policies and procedures should ensure
timely settlement with the executor or administrator of a deceased customer’s account.
Cross-Selling Initiatives
Banks generally develop marketing strategies designed to target various components of their
retail credit portfolios with additional loan or service offers. If developed properly, such
activities often serve to reinforce the relationship with the consumer. To avoid practices that
may be unfair, deceptive, or abusive, however, the bank should ensure that the customers
have not opted out of receiving solicitations; that those customers that are solicited have the
financial resources to support the additional product or service; and that fee-based services
actually add value. The bank should also ensure that all cross-selling initiatives comply with
all applicable fair lending laws and regulations. Otherwise, the bank may create customer ill
will and violate the law by soliciting customers with inappropriate offers or an unmanageable
payment burden.
Retention Strategies
The competitive environment is rife with substitute offers and refinancing opportunities.
Consequently, larger banks have found it beneficial to develop techniques for identifying
profitable customers who may be targeted by competing offers and to contact those
customers proactively to offer them more attractive or enhanced products that typically
include reduced interest rates, higher credit lines, convenience checks, or upgrades to
associated products or services. Banks that do not engage in proactive offer activities
generally develop reactive profitability and performance qualification guidelines for
alternative products or a refinancing should a customer call to close an account.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 33 Credit Card Lending
As with other account management activities, bank management should track the volume of
retention calls (in and out), the “save” rate, and the ongoing performance of those accounts.
This information can be used to assess the profitability of retention initiatives and to adjust
policy.
Other Account Management Tools
Some banks offer “payment holidays,” or skip-a-pay programs, in which customers are given
the option to skip a payment for a billing cycle. This practice has evolved in response to
competition. Although these programs generally may be profitable to the bank because
interest continues to accrue during the billing cycle, they can be detrimental because they
lengthen the repayment term and impair risk analyses that rely on regular payment streams.
“Pay-aheads” occur when a customer makes a payment that exceeds the minimum amount
due and the bank keeps track of the excess payment and reduces future payments
accordingly. Pay-aheads can pose increased risk because they do not require a minimum
payment every month. When banks require customers to make monthly payments, the banks
are able to monitor portfolio quality through more accurate delinquency reporting. Banks
should limit the use of pay-aheads to accounts with low risk characteristics. Banks that
accept pay-aheads on credit card accounts must refer to 12 CFR 1026.53, which sets forth the
requirements for the allocation of the excess payment amounts.
Match-pay programs are yet another type of account management tool. In this program,
frequently used in collections, the bank offers to match all or a part of the payment being
made by the borrower. The bank’s portion of the payment should be limited to an amount
that results in a principal reduction only and should not be so large as to cover finance
charges and fees.
Finally, convenience checks present risks that a bank can minimize by offering the product
only to customers exhibiting low credit risk and low line utilization. Frequently, these checks
come with a low, promotional interest rate to induce customers to use them. Bank
management should make certain that controls and reporting are in place to monitor this
process adequately. For example, convenience checks should have a short-term expiration
date, usually 30 or 45 days. The expiration date limits the risk of a cardholder using the
checks at some date in the distant future when he or she is experiencing a financial hardship.
Bank management should ensure that use of these tools is covered by policy, closely
monitored, and periodically assessed to ensure that the tools are not used to mask
delinquencies. Bank management should ensure that sufficient account management MIS are
in place to depict the condition of the portfolio accurately and completely. Reports and
analyses should identify and explain trends and anomalies. From these reports, management
should be able to discern the level of success of strategies in place and the strategies’ impact
on performance. Examiners should evaluate how bank management uses account
management reports to adjust policies and strategies, as well as the timeliness of management
responses to identified concerns.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 34 Credit Card Lending
Examiners should test various account management strategies through a sampling of
accounts. Information on sample types and sizes is included in appendix A, “Transaction
Testing.”
Securitized Assets
Asset securitization began with structured financing of mortgage loan pools in the 1970s. The
market continued to evolve with the securitization of auto loans and credit card receivables in
the mid-1980s. From that time until the recession that began in 2008, banks and other
financial services providers significantly increased their use of asset securitization to fund
receivable growth, manage their balance sheets, and generate fee income. Although the
recession essentially brought a halt to the securitization market, issuers slowly have reentered
the market. The “Asset Securitization” booklet of the Comptroller’s Handbook discusses in
detail the processes for credit card securitizations and provides procedures for examiners who
are reviewing this area.
Collections
As with other loan portfolios, issuers experience credit and fraud (operational) losses in
credit card portfolios. Reasons for the losses include changes in underwriting standards, mass
marketing of cards in a saturated market, economic downturns that may influence a
consumer’s ability to repay due to unemployment or reduced income, consumer bankruptcy,
information breaches, and identity theft. Collection systems and controls historically have not
kept pace with new account generation, and examiners should focus on this area.
Credit Losses
An effective collection process is a key component of controlling and minimizing credit
losses. It should be effectively managed at each operational level. The problems associated
with an inadequately managed collection function include
• reduced earnings caused by increased loan losses and reduced recoveries.
• inaccurate or late communications of performance concerns to senior management and
the board of directors.
• inaccurate reporting of past-due and charged-off loans, and possibly imprudent
management strategic decisions for the loan portfolio.
• improper use of re-aging (that is, changing the delinquency status of an account), fixed
payment and other workout programs, settlement agreements, or other collection-related
practices.
• insufficient allowance for loan and lease losses (ALLL) caused by weak MIS, inaccurate
past-due figures, and the improper use of re-aging, fixed payment programs, etc.
• inadequate audit trail for collection and recovery activities.
• poorly trained employees, resulting in loss of productivity, collections, and recoveries.
• violations of law and regulations, potentially including fair lending issues.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 35 Credit Card Lending
The collection function is challenging to manage properly because of the size and complexity
of the typical credit card issuing business and the labor-intensive nature of collections.
Consequently, the use of specialized, state-of-the-art technology is increasingly appropriate
to optimize productivity and control overhead costs. Bank management should use current
technology and current and historical information at its disposal to formulate a strategy for
optimizing its collection efforts. In general, the strategy should direct the collection
department’s efforts to those accounts with the greatest risk of loss and the greatest potential
for collection.
Collection departments may be structured in several ways. The most common approaches are
“cradle-to-grave” and back-end/front-end segmentation. In the cradle-to-grave approach, a
collector works with an account from the earliest stage of delinquency through all of the
succeeding stages, or delinquency buckets. This approach is most often used in community
banks in which the collection staff is small. In the back-end/front-end segmentation
approach, some collectors specifically handle early-stage (front-end) delinquency accounts
while others handle later-stage (back-end) accounts. Larger banks often use this approach.
Some banks have chosen to outsource the collection function to an external service provider,
rather than staff an internal department. Because the service provider is collecting the bank’s
accounts, however, there is increased compliance and reputation risk with this type of
activity. If a bank chooses this approach, it should have strong third-party relationship
management processes in place to ensure that the service provider is adhering to all legal and
regulatory requirements and treating the bank’s customers appropriately.30
Collection departments vary significantly in structure and approach. They have at least one
challenge in common, however: the need to closely supervise collection staff. Collection
supervisors should have both collection experience and good management skills. Bank
management should require that collection department supervisors regularly review
collectors’ performance in areas such as number of contacts made, time per contact, and
promises to pay versus dollars received. Such supervisors should also monitor customer
complaints regarding collection and individual collectors’ calls, as well as the documentation
for those calls, to ensure that collectors treat customers fairly and comply with internal
policies and debt collection statutes and regulations.
Examiners should understand how bank management determines the optimum level of
accounts per collector, a crucial factor in preventing and controlling charge-offs. A single
collector can be responsible for hundreds of accounts. A collector’s assigned workload can
vary widely depending on the type of account (bank card or retail) and the technology used.
In addition, front-end (early delinquency) collectors typically handle significantly more
accounts than back-end (severe delinquency) collectors.
Collection strategies determine the specific accounts on which collectors work, the timing of
collection activities, and the manner of the contact (e.g., phone calls, collection letters, or
legal letters). In many banks, collection strategies rely on behavioral scoring models that
 30 Refer to OCC Bulletin 2013-29, “Third-Party Relationships: Risk Management Guidance” (October 30,
2013), which sets forth regulatory guidance for third-party relationships.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 36 Credit Card Lending
predict the likelihood of collection. Some banks also use champion/challenger collection
strategies. Using such information, bank management can effectively direct collection efforts
with an emphasis on dollars at risk. Bank management should maintain close control over
collection strategies because, in some cases, a seemingly minor change can significantly
affect the dollars collected. Examiners should review the bank’s collection strategy process
and reports generated and discuss them with management.
Examiners must have a general understanding of the technologies employed by collection
departments to evaluate a collection department’s effectiveness. Examiners also should
review the bank’s collection training program. Nearly all well-managed collection operations
have formal classroom and on-the-job training programs, which include instruction on new
processes, procedures, or regulatory requirements for new and existing employees.
Management of an account increasingly includes practices such as re-aging, fixed payment,
settlement, and Consumer Credit Counseling Service programs. OCC Bulletins 2000-20,
“Uniform Retail Credit Classification and Account Management Policy: Policy
Implementation,” and 2003-1, “Credit Card Lending: Account Management and Loss
Allowance Guidance,” provide guidance on the use of these collection tools. Although the
following sections describe these tools, examiners should refer to these issuances for specific
details.
Re-Aging
The credit card industry often uses a tool called re-aging, which involves changing the
delinquency status of an account. The term applies to both forward and backward changes,
and re-aging often occurs in both the customer service and collection areas. For example, a
payment on an account subsequently returned for not sufficient funds (NSF) could result in
re-aging the account into a more severe delinquency status, whereas a delinquent account
could be brought current if certain payment requirements are met. This discussion focuses on
instances of collection re-aging in which delinquent accounts are brought current rather than
on one-time customer service actions (e.g., correcting bank errors, cases involving a
borrower who does not have history of becoming delinquent).
The practice of bringing a delinquent account current originated to acknowledge and assist
customers who corrected previous, usually one-time, cash flow problems. To prevent the
accounts from showing as perpetually delinquent, the bank re-ages them to show them as
current. The practice evolved with some issuers inappropriately using re-aging to mask
longer-term or frequent delinquency of troubled borrowers.
Consistent with OCC Bulletin 2000-20, “Uniform Retail Credit Classification and Account
Management Policy: Policy Implementation,” banks that re-age open-end accounts should
establish a reasonable written policy and adhere to it. For example, a policy may provide that
the borrower make at least three consecutive minimum monthly payments or the equivalent
amount before the account can be re-aged to current. Three consecutive payments, rather
than a single lump-sum payment, may be better evidence of the customer’s ongoing
willingness and sustained ability to pay. In addition, the policy may provide that an account 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 37 Credit Card Lending
should have been on the books for at least nine months to be eligible for re-aging and that the
number of re-agings on an account should be limited to one in 12 months and two in five
years. Examiners should
• carefully review the analysis that supports the bank’s decision to re-age accounts and the
bank’s re-aging parameters.
• understand the re-aging program in place and review available MIS reports.
• assess the bank’s re-aging practices, including bank management’s supervision of the
activity.
• sample a number of re-aged accounts to ensure that management practices mirror policy.
Examiners also should consider the bank’s policies and practices in light of OCC Bulletin
2000-20. Sampling techniques for re-aged accounts are included in appendix A of this
booklet.
Because of potential risks associated with re-aging, the practice should be governed by
appropriate policies and procedures. The bank’s re-aging policy should address the
following:
• Approval and reporting requirements.
• Age of the account before it is eligible for re-aging.
• Status of the account while re-aging: closed, blocked, or open.
• Consideration of the borrower’s overall capacity to repay (factors such as income, length
of employment, and other debts) in the re-aging decision.
An improperly managed re-aging program can lead to pools of problem receivables. It also
can understate delinquency and charge-off figures, as well as impede accurate analysis of the
adequacy of the ALLL. Therefore, reports for the re-aging program should be accurate. Bank
management should review regular reports showing both the number and dollar amount of
newly re-aged accounts (current month) and those re-aged within the last 12 months.
According to OCC Bulletin 2000-20, bank management should monitor cumulative historical
data that show the performance of loans that have been re-aged, extended, deferred, renewed,
or rewritten and/or placed in a workout program. Without this information, management
generally cannot determine the effectiveness of re-aging practices. For example, if the bank
ultimately charges off a large percentage of re-aged accounts within a 12-month time frame,
management should determine whether the outcome (dollars collected before charge-off
versus collection costs) justifies the practice.
Fixed Payment Programs
Another practice often used in the collection arena is the fixed payment program. Such
programs are targeted to borrowers with prolonged or severe credit problems in an attempt to
both work with the borrower and to encourage continued repayment. These programs can be
either “temporary” (up to 12 months, after which the account returns to its original terms) or
“permanent” (whereby the account is closed and the balance fully amortized over a term that
generally should not exceed 60 months). Guidance on the terms of temporary programs and 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 38 Credit Card Lending
programs lasting longer than 12 months are addressed by OCC Bulletin 2003-1, “Credit Card
Lending: Account Management and Loss Allowance Guidance.”
Although most banks offer one or more fixed payment or other workout programs, program
characteristics can vary. Programs typically consist of a fixed payment amount over a
specified period of time and often include a reduction in interest rate. Examiners must be
aware that concessions such as reductions in interest rates and delayed payment schedule
adjustments may be troubled debt restructurings (TDR) as defined in Financial Accounting
Standards Board Statement 15, “Accounting by Debtors and Creditors for Troubled Debt
Restructurings,” as amended by ASC 310-10, “Accounting by Creditors for Impairment of a
Loan.” A TDR is a restructuring in which a bank, for economic or legal reasons related to a
borrower’s financial difficulties, grants a concession to the borrower that it would not
otherwise consider.
As would be done for loans and other extensions of credit, estimates of losses on credit card
receivables should reflect consideration of all significant factors that affect the collectability
of the portfolio as of the evaluation date. Examiners should refer to OCC Bulletin 2006-47,
“Allowance for Loan and Lease Losses: Guidance and Frequently Asked Questions on the
ALLL,” and the call report instructions.
Loss rates associated with fixed payment programs are generally higher than those of the
total portfolio because of the borrowers’ financial problems. The bank should have policies
that specify the terms and conditions of fixed payment programs, such as qualifications for
entering the program and how long an account can stay in the program (consistent with OCC
Bulletin 2003-1). Bank management should institute strong controls and ongoing monitoring
and perform regular analyses of the programs to determine whether they ultimately benefit or
harm the bank.
The examiner should assess the prudence of the fixed payment programs in place and the
dollars involved. This assessment should include a sampling of accounts to ensure
consistency with OCC Bulletin 2003-1. Banks generally re-age accounts to current on receipt
of payments equivalent to three contractual payments at the newly agreed rate and amount.
Examiners should review the bank’s programs to determine whether consumers are just
moved from one temporary program to another and whether enrollment in a program results
in an inappropriate adjustment to the delinquency buckets. As with the review of re-aged
accounts, sampling techniques for fixed payment programs are also included in appendix A,
“Transaction Testing.” As part of transaction testing, examiners should determine whether
account files document whether a consumer’s difficulty is temporary or permanent. If the
difficulty is temporary, file documentation should support the temporary nature of the
hardship and whether a temporary fixed payment program was appropriate. For example, in a
temporary workout situation system, notes for the file might document that the borrower was
out of work with a medical problem and returned to work in two months without further loss
of income. In this case, a temporary payment program might be appropriate. If the borrower
sustained a longer-term issue that resulted in a diminished ability to repay, however, a
permanent workout may be appropriate.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 39 Credit Card Lending
There are several common issues examiners encounter when reviewing workout programs.
Collectors may not adequately assess and/or document the severity of the cardholder’s
financial difficulty. If borrowers are routinely placed in temporary hardship programs when
their financial problems are of a permanent nature, it may mask the true condition of the
portfolio. High default rates in workout programs may call into question the assessment of
the severity or long-term nature of a cardholder’s financial difficulty. In this case, examiners
should question the effectiveness of collection practices around workout programs and, if
appropriate, criticize the practices. In addition, some bank policies allow borrowers to move
from one workout program to another, often when a borrower does not perform or “breaks”
the workout, without adequate analysis supporting this transition. In general, cardholders
should be placed in the workout program with payment terms appropriate to their hardship.
The total length of time a borrower is in a workout program, on a combined basis, generally
should not exceed 60 months.31
Settlement Programs
Settlement programs are another type of workout program in which the bank agrees to accept
less than the full balance due from a borrower in full satisfaction of the debt. As with any
other workout program, collectors should determine the borrower’s ability to repay under the
settlement terms.
When there is a settlement agreement, the portion of the balance that will not be paid by the
borrower should generally be charged off when the agreement is reached. If a bank’s
technology does not allow for charge-off of a partial balance, the partial balance should be
fully reserved in the bank’s ALLL. On receipt of the final settlement payment or if the
borrower misses a payment under the agreement, the remaining balance should be charged
off in full within 30 days.
Consumer Credit Counseling
As part of their collection efforts, many banks also work with consumer credit counseling
(CCC) programs. CCC organizations are typically independent third parties that help
consumers work through their financial difficulties.
A consumer’s acceptance into a CCC program is often based on a counselor’s determination
that the consumer’s financial situation is salvageable. If accepted, the consumer generally
agrees to cancel all credit cards and other open unsecured lines of credit, develop and adhere
to a budget (with counselor guidance), and make debt payments as agreed. The consumer
credit counselor then notifies creditors that the consumer has been accepted into the program
and negotiates reduced payment terms with each creditor. Terms vary by creditor, with some
requiring the full payment amount and others reducing interest and principal payments
significantly in an attempt to stop the account from going to loss. As with the fixed payment
programs, bank management should evaluate these accounts to determine whether they meet
 31 Refer to OCC Bulletin 2003-1, “Credit Card Lending: Account Management and Loss Allowance Guidance.”
Exceptions should be clearly documented and should be supported by compelling evidence that less
conservative terms and conditions are warranted.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 40 Credit Card Lending
the standards for a TDR. If so, the bank should employ proper accounting practices. Refer to
the “Fixed Payment Programs” section of this booklet for further information and existing
OCC instructions.
After acceptance into a CCC program, consumers generally then make their payments
directly to the CCC organization, which pays the creditors. CCC programs can run for up to
60 months and are considered “permanent” workout programs under OCC Bulletin 2003-1.
After receiving confirmation of a consumer’s acceptance into the CCC program and the
typical three consecutive payments (or the lump-sum equivalent) under the plan, a creditor
normally re-ages the consumer’s account to a current status, if the account is otherwise
delinquent. At this point, the creditor generally waives any late and over-limit fees and ceases
all collection efforts, as long as the account complies with the renegotiated terms. If an
account goes delinquent again for any significant period of time, it usually reverts to the
original contract terms, collection efforts commence, and it is dropped from the CCC
program.
Banks should have a policy regarding CCC accounts and appropriate systems to properly
account for related transactions with the CCC organization. Banks typically assign an
individual or specific group to supervise and monitor its CCC accounts. The bank should
ensure that all CCC accounts are properly identified to enable accurate reporting of CCC
delinquencies and charge-offs and should incorporate CCC information into the appropriate
loan risk grades and into ALLL calculations. The bank should have a process to identify
CCC accounts that qualify as TDRs to ensure that the ALLL for these accounts is determined
in accordance with ASC 310-10, “Accounting by Creditors for Impairment of a Loan.”
MIS for Collections
The collection area typically generates many MIS reports to help manage the risks associated
with this activity. Regular MIS reports for each collection program are an important aid in
proper supervision. Executive management should regularly review key MIS collection
reports. Management should be able to identify and quantify all collection program specifics,
such as the number of re-agings on an account. OCC Bulletin 2000-20, “Uniform Retail
Credit Classification and Account Management Policy: Policy Implementation,” states that,
to be effective, MIS should also monitor and track the volume and performance of loans that
have been re-aged, extended, deferred, renewed, or rewritten and/or placed in a workout
program. MIS provide the mechanism to assess consistency with OCC Bulletin 2007-45,
“Identity Theft Red Flags and Address Discrepancies: Final Rulemaking,” and to assess
compliance with rules implementing sections 114 and 315 of the FACT Act
(15 USC 1681m(e) and 15 USC 1681c(h), respectively), 12 CFR 41, and any other
applicable laws and regulations. Further, MIS should provide management with the ability to
identify and report suspicious activities. If a program is not working effectively, management
should take steps to discontinue or modify it. Examiners should evaluate the bank’s MIS for
pertinent information and accuracy and may need to criticize any absence of appropriate
tracking and monitoring.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 41 Credit Card Lending
One report, called the “rollover,” or “roll-rate” report, is particularly important. Through this
report, bank management can review the number and dollar volume of accounts that move
from current to 30 days delinquent, 30 to 60 days delinquent, etc. This information aids
management in projecting accurately the charge-off rates as far as six months into the future
and informs decisions regarding collection staffing levels.
Delinquency and charge-off reports serve as valuable tools in evaluating collection
effectiveness. Bank management should review these reports for the entire portfolio as well
as on a program-by-program basis. Many credit card operations report delinquencies using
two formats: end-of-month (EOM) and sum-of-cycle (SOC). EOM delinquencies are used for
call report purposes and reflect outstanding delinquencies at month-end as a percentage of
outstanding receivables. SOC reports compute delinquencies for each billing cycle, then
aggregate these cycles to determine delinquency for the total portfolio. Unlike EOM reports,
SOC reports ignore the “cleaning up” of delinquencies between the end of the cycle date and
the end of the month.
Bank management may find reports that analyze delinquencies and charge-offs on a “lagged”
basis useful, especially if a portfolio has experienced significant growth. Such analyses
calculate current delinquency and charge-off figures as a percentage of receivables
outstanding six or 12 months prior. A “block” or “status code” report provides valuable
information for reviewing the composition of the portfolio (e.g., the number and dollar
amounts of fixed-payment, bankruptcy, fraud, deceased, and canceled accounts). Other
reports should include actual versus budgeted performance, impact of changes in collection
strategies, and performance of behavioral or other scoring models.
Delinquency, Classification, and Charge-Off Policies
Bank management should regularly review the quality of the portfolio through a variety of
means, including past due, charge-off, and profitability reports. Management should be able
to quickly identify trends in the portfolio and react appropriately.
Guidance on account classification and charge-off practices is provided by OCC Bulletin
2000-20, “Uniform Retail Credit Classification and Account Management Policy: Policy
Implementation,” which, in general, advises that credit card accounts be charged off when
they become 180 days delinquent. Accounts that are placed in long-term amortizing workout
programs should be charged off at 120 days. The bulletin also addresses accounts that are
affected by bankruptcy, fraud, and death, and examiners should review this issuance closely
when assessing a bank’s collection activities.
All accounts that are 90 to 180 days delinquent should be classified as substandard.
Examiners are not precluded from classifying additional portfolio segments as substandard,
however, if a review of credit information and loss performance indicates that such
classification is warranted. For example, a subprime program in which the roll-to-loss rate
from 30 days delinquent is between 30 percent and 50 percent may indicate a need to classify
these assets substandard rather than waiting until they are 90 days delinquent, when the rollto-loss
rate is 90 percent. Likewise, it may be appropriate to charge off these accounts sooner 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 42 Credit Card Lending
than 180 days if roll-rate information suggests that almost 100 percent of the accounts roll to
loss earlier in the cycle.
Nonaccrual Status (Updated January 6, 2017)
Banks should follow the Federal Financial Institutions Examination Council’s “Instructions
for Preparation of Consolidated Reports of Condition and Income” (call report instructions)
when determining the accrual status for consumer loans. As a general rule, banks shall not
accrue interest, amortize deferred net loan fees or costs, or accrete a discount on any asset if
• the asset is maintained on a cash basis because of deterioration in the financial condition
of the borrower,
• payment in full of principal or interest is not expected, or
• principal or interest has been in default for a period of 90 days or more unless the asset is
both well secured and in the process of collection.32
The call report instructions provide two exceptions to the general rule:33
(1) Consumer loans and loans secured by a one- to four-family residential property need not
be placed in nonaccrual status when principal or interest is due and unpaid for 90 days or
more. Nevertheless, consumer and one- to four-family residential property loans should
be subject to other alternative methods of evaluation to assure that the bank’s net income
is not materially overstated. To the extent that the bank has elected to carry a consumer or
one- to four-family residential property loan in nonaccrual status on its books, the loan
must be reported as nonaccrual in the bank’s call report.
(2) Purchased credit-impaired loans need not be placed in nonaccrual status when the criteria
for accrual of income under the interest method specified in ASC Subtopic 310-30,
“Receivables – Loans and Debt Securities Acquired with Deteriorated Credit Quality,”
are met, regardless of whether the loans had been maintained in nonaccrual status by the
seller. For purchased credit-impaired loans with common risk characteristics that are
aggregated and accounted for as a pool, the determination of nonaccrual or accrual status
should be made at the pool level, not at the individual loan level.34
 32 An asset is “well secured” if it is secured (1) by collateral in the form of liens on or pledges of real or
personal property, including securities, that have a realizable value sufficient to discharge the debt (including
accrued interest) in full, or (2) by the guarantee of a financially responsible party. An asset is “in the process of
collection” if collection of the asset is proceeding in due course either (1) through legal action, including
judgment enforcement procedures, or, (2) in appropriate circumstances, through collection efforts not involving
legal action which are reasonably expected to result in repayment of the debt or in its restoration to a current
status in the near future.
33 For more information, refer to the “Nonaccrual Status” entry in the “Glossary” section of the call report
instructions. This entry describes the general rule for the accrual of interest, as well as exceptions for retail
loans. The entry also describes criteria for returning a nonaccrual loan to accrual status.
34 For more information, refer to the “Purchased Credit-Impaired Loans and Debt Securities” entry in the
“Glossary” section of the call report instructions.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 43 Credit Card Lending
As a general rule, a nonaccrual loan may be restored to accrual status when
• none of its principal and interest is due and unpaid, and the bank expects repayment of
the remaining contractual principal and interest, or
• it otherwise becomes well secured and is in the process of collection.
The OCC’s Bank Accounting Advisory Series and the “Rating Credit Risk” booklet of the
Comptroller’s Handbook provide more information for recognizing nonaccrual loans,
including the appropriate treatment of cash payments for loans on nonaccrual status.
Recoveries
Recoveries represent collection activities conducted after an account is charged off. The rate
of recovery depends on many factors, including
• previous collection efforts.
• depth and experience of staff.
• adequacy of systems and controls.
• use of technology.
Recovery activities are generally conducted internally and then out-placed to collection
agencies after several months. When out-placing accounts, the bank should maintain strict
controls and appropriate systems to evaluate each agency’s performance. Collection agencies
receive a percentage of the dollars collected, typically between 30 percent and 60 percent.
The amount varies based on whether the agency is the primary collector (the first to work the
accounts) or the secondary or tertiary collector. Fees are lowest for the primary agency and
highest for the tertiary agency. A bank should periodically rotate out-placed accounts among
agencies to ensure that the accounts are actively and appropriately worked.
When banks select agencies to which they out-place accounts, the banks should perform due
diligence to ensure that an agency is, among other things, properly licensed, bonded, and
insured. Banks also should have systems to monitor the agencies on an ongoing basis to
ensure that the agencies operate prudently. Bank management should follow the guidance in
OCC Bulletin 2013-29, “Third-Party Relationships: Risk Management Guidance,” when
working with outside parties to collect accounts.
Consumer Debt Sales
As providers of consumer credit, banks lend money to be repaid with interest. Banks
underwrite the loans and price them according to the risk associated with the type of lending
and the customers’ creditworthiness. A percentage of the loans that banks make goes unpaid.
Under guidelines set out in OCC Bulletin 2000-20, “Uniform Retail Credit Classification and
Account Management Policy: Policy Implementation,” banks should charge off open-end
credit at 180 days past due. Even though the bank has charged off the loan, the borrower
generally continues to have an obligation to repay the debt. At that point, the bank faces a
business decision on how to recover the loss or whether to pursue collection at all.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 44 Credit Card Lending
The majority of debt that banks charge off and sell to debt buyers is credit card debt, but
banks also sell to debt buyers other delinquent debts, such as auto, home equity, mortgage,
and student loans. Most debt-sale arrangements involve banks selling debt outright to debt
buyers. Banks may price debt based on a small percentage of the outstanding contractual
account balances. Typically, debt buyers obtain the right to collect the full amount of the
debts. Debt buyers may collect the debts or employ a network of agents to do so. Notably,
some banks and debt buyers agree to contractual “forward-flow” arrangements, in which the
banks continue to sell accounts to the debt buyers on an ongoing basis. This section focuses
specifically on debt sales. Many of the principles, however, also apply when a bank hires a
third party to collect debt on its behalf.
When a bank sells consumer debt, the bank should have policies, procedures, and practices
that help ensure that any third party purchasing the bank’s consumer debt for its own
collection treats customers fairly and consistently, in accordance with the bank’s expectations
and applicable law. Increased risk most often arises from poor planning and inferior
performance or service on the part of the debt buyer, and this may result in legal costs or loss
of business for the bank. Selling debt to a debt buyer can significantly increase a bank’s risk
profile, particularly in the areas of operational, reputation, compliance, and strategic risks.
• Operational risk: Inadequate systems and controls can place the bank at risk for selling
debt with inaccurate information regarding the characteristics of accounts.
• Reputation risk: When banks sell consumer debt to debt buyers that engage in practices
perceived to be unfair or detrimental to customers, banks can lose community support
and business.
• Compliance risk: This risk exists when banks do not appropriately assess current and
ongoing debt buyer collection practices for compliance with laws, fair treatment of
customers, or the bank’s policies and procedures.
• Strategic risk. Decisions to sell debt to debt buyers should be carefully analyzed by
examiners to assess consistency with the bank’s strategic goals and whether capable
management and staff are in place to perform due diligence and carry out debt sales.
Examiners are encouraged to refer to OCC Bulletin 2014-37, “Consumer Debt Sales: Risk
Management Guidance,” for guidance as they review bank debt sales activities. Likewise,
examiners should refer to OCC Bulletin 2013-29, “Third-Party Relationships: Risk
Management Guidance,” which sets forth guidance for effectively managing risks associated
with vendors and third-party service providers, including third-party service providers
collecting debt on behalf of the bank (debt placement relationships). Additionally, examiners
should complete a careful review of these sales to assess that they are consistent with
generally accepted accounting principles (GAAP).
Federal statutes applicable to debt sales include the following:
• FDCPA: This applies to debts incurred primarily for the consumer’s personal, family, or
household purposes. Under the FDCPA, “debt collector” is defined broadly to encompass
debt buyers working on behalf of original creditors, including banks.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 45 Credit Card Lending
• FCRA: The FCRA, which is implemented by Regulation V, regulates the collection,
dissemination, and use of consumer information, including consumer credit information.
• Gramm–Leach–Bliley Act (GLBA): Certain provisions of the GLBA and Regulation P,
which implements the GLBA, require banks to provide consumers with privacy notices at
the time consumer relationships are established and annually thereafter. In addition, this
law imposes limitations on banks’ sharing of nonpublic personal information with debt
buyers.
• ECOA: The ECOA and its implementing regulation, Regulation B, prohibit
discrimination in any aspect of a credit transaction on a “prohibited basis.” The
prohibition against discrimination in any aspect of a credit transaction on a prohibited
basis includes collection procedures.
• FTC Act: Section 5 of the FTC Act prohibits UDAP in or affecting commerce. Public
policy may also be considered in determining if acts or practices are unfair.
• Dodd–Frank Act: Section 1036(a)(1) of the Dodd–Frank Act, 12 USC 5536(a),
prohibits a covered entity from engaging in UDAAP.
Fraud Control
Fraud is a continuing problem with credit card programs. By its very nature, the product is an
easily obtainable, unsecured line of credit managed by the consumer, making it an ideal
mechanism for fraud. The bank card associations, issuers, and acquirers, the U.S. Postal
Service, and other entities have strengthened systems and controls to reduce fraudulent
activities. Despite significant advances in detection, however, fraud—specifically identity
theft—continues to be a major issue in the credit card industry.
Bank management should have appropriate systems and controls in place to control fraud
losses. Systems and controls should include procedures for reporting suspicious activity. The
proper training of bank employees regarding fraud systems and controls, fraud recognition
and handling, and accurate MIS reporting are important for maintaining fraud losses at or
below industry averages. Training programs for this area should include the “Identity Theft
Red Flags and Address Discrepancies” rules implementing sections 114 and 315 of the
FACT Act, 12 CFR 41, as well as identification and reporting of suspicious activities.
Fraud can be orchestrated in many ways. Lost or stolen cards and nonreceipt of issued cards
represent a large percentage of all fraud reported. In recent years, however, thousands of
consumers have been affected when their card account numbers were illegally obtained from
retailers’ sales records and then used for unauthorized purchases. Banks must implement a
comprehensive written information security program designed to ensure the security and
confidentiality of customer information.
35 A bank should make the OCC aware as soon as
possible when it becomes aware of a security breach involving sensitive customer
information. Examiners should assess the adequacy of the bank’s assessment of the security
breach, the magnitude of the event, and the appropriateness of its response, including its
plans to notify customers.
 35 Refer to 15 USC 6801 and 6805(b) of the GLBA and 12 CFR 30, appendix B.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 46 Credit Card Lending
Bank card associations track fraud according to type, and most issuers follow this or a similar
format in reporting fraud in their internal MIS reports. Reporting specific information on
types of fraud allows a bank to better identify its points of greatest risk. If a bank does not
distinguish fraud losses by type, examiners should discuss the benefits of such reporting with
bank management.
Card issuers should review their average fraud losses to determine whether their staff
identifies fraudulent activities in a timely manner. If an issuer has inadequate systems and
controls to identify fraud, fraudulent activity is likely to continue for longer periods and
result in higher losses.
Card issuers have pursued the following activities to deter and reduce fraud:
• Sorting mail outside the facility where the mail was initiated.
• Instituting call-to-activate requirements for new cards and reissued cards.
• Implementing pattern recognition programs and systems.
• Developing neural networks (an extension of risk scoring techniques used in part to
identify fraudulent transactions) or expert systems.
• Extending the time after which cards are reissued from two years to three years to reduce
the number of cards in the delivery system.
• Designating a special customer service group to handle reports of lost or stolen cards.
• Increasing the level of payment review to include all checks over a certain dollar amount,
regardless of whether there is a payment coupon.
• Introducing EMV (Europay MasterCard Visa) standard payment cards (referred to as
chip-and-PIN or chip-and-signature cards) to reduce fraud at the point of sale.
Most large issuers maintain a dedicated fraud staff that supervises the many actions that
occur when a cardholder notifies the issuer or the issuer becomes aware that fraud has
occurred. These activities include
• preparing a lost or stolen card report from the cardholder and advising the cardholder to
destroy additional cards. The report may include the account number, name, fraud type,
address, number of transactions, dollar amount of fraud, charge-off month and date,
description of fraudulent activity, corrective action taken, if any, name of preparer, and
name of manager signing off on the report.
• blocking the account and placing it on an exception file with its own unique block codes,
depending on its processor.
• preparing a request to issue new cards to the cardholder. This may include reviewing
activity in the blocked account and transferring legitimate transactions to a replacement
account.
• setting up a file for investigation of fraud accounts. This may include requesting draft
copies of fraudulent items and challenging the cardholder’s claims that items are
fraudulent, if those claims are suspect.
• reviewing and initiating appropriate steps to charge back items to other parties
responsible for chargebacks. This may include preparing fraud notifications to applicable 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 47 Credit Card Lending
card networks (e.g., Visa or MasterCard), investigating and documenting fraudulent
cards, and prosecuting culprits, if possible.
• investigating and resolving address or other types of discrepancies.
• filing suspicious activity reports, if required.
Issuers should have adequate systems and controls in place to recognize fraudulent activities
in a timely manner, to block accounts when appropriate, to prevent future authorizations, and
to file the proper reports. The timing of the block date is important, as the vast majority of
fraud losses occur on or before the block date, and losses incurred after the block date usually
have significantly lower transaction sizes.
According to OCC Bulletin 2000-20, fraudulent loans should be classified as loss and
charged off no later than 90 days after discovery or when the account is 180 days delinquent,
whichever is sooner. Losses resulting from fraud committed by someone other than the
cardholder should be charged to other noninterest expense. Losses resulting from fraud
committed by the cardholder should be charged to the ALLL.
Purchased Credit Card Relationships
Purchased credit card relationships (PCCR) are intangible assets created when a bank
purchases a credit card portfolio at a premium from a third party. Generally, when a
performing credit card portfolio is purchased, a large part of the premium (the purchase price
over the par value of the credit card receivables acquired) is related to the PCCR. The PCCR
represents the right to conduct ongoing credit card business dealings with the cardholders.
Such relationships arise when the reporting bank purchases existing credit card receivables
and has the right to provide credit card services to those customers. PCCRs may also be
acquired when the reporting bank purchases an entire depository institution. The PCCR
represents the value of the profit coming from the established card relationships acquired,
typically discounted at the acquiring institution’s cost of capital. This intangible is amortized
over its expected life. For more information on PCCRs, refer to appendix J of this booklet.
Not every credit card portfolio that is purchased results in a PCCR. The cost of acquiring a
credit card portfolio can vary widely, and a bank may even purchase a portfolio at a discount.
The purchase price can be determined by a variety of factors that, in the aggregate, reflect the
expected cash flows of the portfolio. Some of the main factors considered are the yield,
attrition rates, portfolio performance, funding rates, and processing costs.
Most credit card portfolio purchasers maintain automated models that bank management can
load with its best estimates of how the purchased portfolio will perform. The card portfolio
data are typically obtained directly from the sellers (or their investment bankers) and are used
to determine the initial bid on the portfolio. If the bank is selected to perform a due diligence
examination (because it offered one of the highest bids), it then modifies the model with
enhanced data obtained during the due diligence review. The model generally creates cash
flow data, income statements, balance sheets, equity flows, and other information that
permits the purchaser to determine an appropriate value for the portfolio, usually based on an
internal earnings hurdle rate (the minimum acceptable rate of return on a capital investment 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 48 Credit Card Lending
project). Models typically include discounted cash flow models, discounted capital flow
models, and return-on-asset models. (Refer to appendix J for a detailed discussion on the
analysis of PCCRs.)
Allowance for Loan and Lease Losses
The methods used to establish and maintain the ALLL in credit card portfolios varies among
banks. Examiners must review the bank’s method to determine whether it is reasonable,
adequately documented, and consistent with OCC Bulletin 2006-47, “Allowance for Loan
and Lease Losses: Guidance and Frequently Asked Questions on the ALLL.” Examiners
must recognize that no method can determine the appropriate reserve level with absolute
precision; instead, reasonable and supportable estimates must be made by bank management
based on careful analysis of the portfolio. For more information on reviewing the adequacy
of and the methodology for determining the appropriate level for the ALLL and examination
procedures, refer to the “Allowance for Loan and Lease Losses” booklet of the Comptroller’s
Handbook.
Examiners must determine whether the bank’s methodology for determining its ALLL
adequately estimates losses in the portfolio. OCC Bulletin 2006-47 defines “estimated credit
losses” as “an estimate of the current amount of loans that it is probable the bank will be
unable to collect given facts and circumstances as of the evaluation date.” Estimated losses
for pools of homogeneous loans, such as credit card portfolios, are governed by ASC 450-20,
“Loss Contingencies” (formerly Statements of Financial Accounting Standards (SFAS) 5). In
general, for credit card portfolios, the bank should have a supportable and well-documented
analysis that segments the portfolio and computes loss histories for each segment, applies
adjustments for internal and external qualitative factors, and results in an ALLL balance that
is prudent and appropriate (i.e., sufficient to absorb estimated credit losses).
For estimated credit losses on accrued interest and fees that are reported as part of the
respective loan balances on the bank’s balance sheet, the associated ALLL should be
evaluated under ASC 450-20.
One method commonly used to estimate losses in credit card portfolios is the roll-rate
analysis. When using this method, bank management should segment the portfolio into
appropriate product types. Further segmentation is possible when defining characteristics are
present that apply to additional homogeneous pools within the credit card portfolio. Bank
management should then track the rates at which loans roll through the delinquency buckets
to determine estimated losses based on performance history. For example, management may
track how many loans roll from current to 30 days delinquent, then how many of the 30-day
delinquent loans roll to 60 days delinquent, and so on. Management then may assess broader
economic factors to estimate how external influences may affect portfolio performance. This
is a simplistic example of estimating losses using the roll-rate process. Many large banks use
some form of roll-rate analysis, often with granular segmentation of the various portfolios.
Environmental factors are likely to affect domestic portfolios differently than international
portfolios.
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 49 Credit Card Lending
Whatever the method, the ALLL analysis should be commensurate with the size and
complexity of the credit card portfolio and provide sufficient support to the portion of the
bank’s allowance that is allocated to credit cards. Generally, institutions should use at least
an “annualized” or 12-month average net charge-off rate when estimating credit losses.
Reserving for Rebate Programs
With the fierce competition to provide credit cards, issuers have become increasingly
aggressive in account acquisition. The sheer number and various types of issuers—such as
nonbank card issuers, Competitive Equality Banking Act (CEBA) credit card banks, and
cobranding partners—have intensified marketing to the consumer. Most issuers, either
directly or through a partnership arrangement, now offer some type of rebate or rewards
program to cardholders. Rebates may be in the form of cash; free gas, hotel stays, or airline
tickets; monies toward car purchases; and other items.
The cobranding partnership contract is very important in determining the issuer’s costs,
marketing requirements, and liabilities, if any. In most arrangements, the partner has
contingent liability based on a rebate formula involving cardholder purchase dollar volume.
In some cases, however, the contract could be negotiated to impose on the issuer some of the
contingent liability on the rebate program. The bank should factor contract terms, particularly
covering liability, into pricing the partnership relationship. If the issuer has contingent
liability, it should reserve for the liability, as described in this section.
36
Most major issuers now offer general purpose cards (including affinity and cobranded cards)
that contain rebate features. In these cases, the contingent liability pertaining to the rebate
redemption rests with the issuer. Because of this, the issuer should reserve for this future
redemption liability, and examiners must determine the rebate reserve’s adequacy, as well as
the reasonableness of the reserve method.
If the issuer has contingent liability on any rebate program, examiners should approach the
analysis in a manner similar to evaluating the adequacy of the ALLL. The issuer should have
an accounting policy that governs the rebate reserve method.
37 If there is no policy,
examiners should discuss the need for a policy with bank management. The policy should
address issues such as
• general ledger account under which the reserve will be located.
• account under which the expense will be located.
• how monthly accruals will be determined.
• maintenance of subsidiary ledgers.
• how often formal analysis of the reserve will be prepared.
• management sign-off to attest to reserve adequacy.
• management sign-off to change the reserve methodology.
 36 Refer to OCC Bulletin 2013-29, “Third-Party Relationships: Risk Management Guidance.”
37 Information on accounting for rebates can be found in guidance issued by Emerging Issues Task Force
(EITF).
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 50 Credit Card Lending
• handling of redemptions.
• handling of over- and under-reserve levels.
• if outside vendors are used in the redemption process, interface of databases in
connection with points accounting, redemption transactions, etc.
In analyzing the adequacy of a rebate reserve, examiners should review the method and
determine how long the program has existed and whether rebate reserve levels differ as the
program ages. Examiners should also determine whether there have been any significant
modifications regarding rebates or rebate reserve methodology. The type of product the
issuer or retailer promotes has a material impact on the type of reserve method that bank
management uses. For example, the rebate reserve method for a program that allows for the
accumulation of points toward a purchase may be different from a program that annually
rebates 5 percent of net purchase sales in cash. Also, many programs have rebate limitations
during specific time periods. If no limitations are apparent, examiners should discuss this
with bank management and evaluate what, if any, risk the absence of limitations poses to the
issuer’s financial condition.
Outside vendors may be used to provide a variety of services for rebate programs, including
accounting and redemption. Examiners should assess what outside parties are involved in the
rebate operation, how information is passed between systems, and how payments are
transacted.
In addition, examiners should be mindful of the operational and reputation risks associated
with rebates and rewards programs. If a cardholder can choose from multiple rewards on a
single card, these risks may grow significantly. Banks should have strong controls in place to
ensure that cardholders actually receive the rebates or rewards they signed up for, that
cardholders receive proper disclosures, and that rewards are correctly calculated.
Profit Analysis
Credit card operations offer banks substantial opportunities for profit because credit card
portfolios can generate returns on assets that far exceed those of other product lines. Profit
margins on credit card accounts can be overstated, however, and examiners should perform a
thorough analysis of a credit card operation’s financial statements to draw accurate
conclusions. Moreover, profitability can vary, as it is influenced by cyclical trends in the
consumer retail area and the economy in general.
Examiners should begin their analysis with a review of the credit card operation’s strategic
plan. Strategic goals can vary among issuers. For instance, credit card operations owned by
retailers may be concerned primarily with increasing incremental sales of the retailer. The
card operations may lower their credit standards to put more of the retailer’s cards in
circulation. Although this increases sales for the retailer, lower standards may reduce the
profitability of the credit card operation because it could lead to higher credit losses.
The credit card operation should have a system to measure overall profitability, including
direct and indirect costs. The operation should have detailed budgets that are compared 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 51 Credit Card Lending
against actual results, with significant variances investigated. The bank should periodically
estimate the impact of potential economic changes, competition, and legislative issues on the
portfolio. Lastly, bank management should prepare pro forma financial statements on major
new product rollouts or modifications of significant terms on existing product lines to
identify potential effects on income streams.
The credit card operation should prepare profit analyses for the total portfolio and for each
individual portfolio or program. In addition, it is increasingly appropriate for operations to
manage profit levels at the individual account level. As profit margins continue to narrow
and account retention becomes increasingly important, assessing account-level profitability
becomes more important. Account-level data can help bank management focus its retention
efforts by determining such things as accounts on which to waive annual membership fees.
Most major issuers have separate finance areas to supervise the accounting of income and
expenses. These areas should have in place appropriate MIS reports that detail income and
expenses for executive management summary reports. Good MIS are crucial to ensuring that
management has an accurate profitability picture. The finance area generally is responsible
for coordinating and preparing the budget and strategic goals, as well as generating any
reports to the parent company; payment card networks, such as Visa, MasterCard, or
American Express; and regulatory agencies.
Profitability among credit card operations varies widely based on a number of factors, such
as management competence, risk appetite, products offered, affinity or cobranding
relationships, and the method used to report various costs. Bank management should have
strong accounting and reporting systems in place to supervise the business effectively. (Refer
to appendix I of this booklet, “Profit Analysis,” for examples of ways to examine the
profitability of credit card operations.)
There are several common measures of the overall profitability of a credit card portfolio.
These include return on average assets (ROAA), return on equity (ROE), and income per
billed account. ROE measures help determine the market’s perception of the bank’s financial
performance. They can, however, vary significantly depending on securitization volumes and
capital leverage. Consequently, the use of ROE as the sole measure to gauge financial
performance for credit card operations should be scrutinized by examiners.
Examiners must know the sources of a credit card operation’s income and expenses to
analyze its profitability. Some of the basic components of income in a credit card operation
are finance charges, annual and service fees, and interchange fees. Some credit card
operations receive service fees and residual income from securitized portfolios. Interest rates
vary widely depending on products, borrowers’ risk profiles, competition, and state usury
laws. The annual and service fee component of income generally includes fees assessed to
the customer for use of the card. Annual fees vary and generally are tailored to the perceived
value of the card and associated enhancements, such as travel insurance or check cashing
privileges. Service fees are generally fees imposed on transactions such as cash advances,
late payments, and over-limit transactions. An interchange fee is a fee to the issuer that is
extracted from the discount fee paid by a merchant who accepts a credit card transaction. 
Version 1.2 Introduction > Risk Management
Comptroller’s Handbook 52 Credit Card Lending
For most credit card operations, one basic component of expenses, the cost for account
acquisition, continues to rise, particularly for accounts associated with rewards programs.
The value of the reward “bonus” required to lure a new creditworthy account holder
continues to rise significantly and, along with it, the cost of that bonus. Other expenses for
most credit card operations include credit processing, card issuance, authorizations,
collections, loan-loss provisions, cardholder servicing and promotion, cardholder billing,
payment processing, and fraud investigations. Other possible expenses include payments to
affinity and cobranding partners and reserves for rebate programs, where applicable.
Credit card operations tend to be one of the costlier areas of a bank. The small size of
individual accounts and the high transactional volume create higher costs per account. There
are also costs associated with data processing, whether conducted in-house or contracted out
to a third party.
Cost of funds is a major expense item that can compose up to half of an issuer’s total expense
distribution. Cost of funds can vary depending on the funding sources used by the bank, as
well as the bank’s condition and reputation in the market. Many large credit card issuers use
securitization as a source of funding. Examiners should discuss trends in funding costs and
composition with the bank and investigate unusual variances.
In reviewing income and expense categories, it is helpful to compare the bank’s performance
against peer data. Examiners should inquire whether the bank has recent industry cost
studies. Notably, bank card associations periodically provide their members with cost studies
and other industry data.